// components/ExternalLink.vue
<template>
  <a
    :href="href"
    :target="target"
    rel="noopener"
    @click="$emit('click')"
    @focus="$emit('focus')"
    ><slot
  /></a>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    to: {
      type: String,
      default: "",
    },
    target: {
      type: String,
      default: "_blank",
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    href(): void | string {
      if (this.disabled) {
        return;
      }
      return this.to;
    },
  },
});
</script>

// src/components/layout/ExternalLink/ExternalLink.tsx
import React from "react";

type Props = {
  children: React.ReactNode;
  disabled?: boolean;
} & React.DetailedHTMLProps<
  React.AnchorHTMLAttributes<HTMLAnchorElement>,
  HTMLAnchorElement
>;

const ExternalLink: React.FC<Props> = (props: Props) => {
  const { children, disabled } = props;
  const attributes = {
    ...props,
    target: "_blank",
    rel: "noopener noreferrer",
  };

  if (disabled) {
    delete attributes.href;
  }

  return <a {...attributes}>{children}</a>;
};

export default ExternalLink;
