// src/components/layout/ErrorBase/ErrorBase.tsx
import React from 'react';
import styles from './errorBase.module.scss';
import Link from 'next/link';

type Props = {
  containerClassName?: string;
  mainMessage: string;
  subMessage?: string;
};

const ErrorBase: React.FC<Props> = ({ containerClassName, mainMessage, subMessage }) => {
  return (
    <div className={`-mb-48 text-white w-full bg-center bg-cover ${containerClassName}`}>
      <div className="bg-dark bg-opacity-75 w-full h-screen flex flex-col items-center justify-center text-center pb-16">
        <h1 className={`heading-title ${styles.heroTitle}`}>{mainMessage}</h1>
        <h2 className={styles.heroSubtitle}>{subMessage}</h2>
        <Link href="/" className={`button ${styles.button}`}>
          Go to Home Page
        </Link>
      </div>
    </div>
  );
};

export default ErrorBase;

// components/errors/error-base.vue
<template>
  <div class="text-white w-full bg-center bg-cover" :class="containerClass">
    <div
      class="
        bg-dark bg-opacity-75
        w-full
        h-screen
        flex flex-col
        items-center
        justify-center
        text-center
        pb-16
      "
    >
      <h1 class="heading-title hero-title">{{ mainMessage }}</h1>
      <h2 class="hero-subtitle">{{ subMessage }}</h2>
      <nuxt-link to="/" class="button">Go to Home Page</nuxt-link>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    containerClass: {
      type: String,
      default: "",
    },
    mainMessage: {
      type: String,
      default: "",
    },
    subMessage: {
      type: String,
      default: "",
    },
  },
});
</script>

<style scoped>
.hero-title,
.hero-subtitle {
  animation: 3s appear;
}

.hero-title {
  @apply text-white;
}

.hero-subtitle {
  @apply font-light text-4xl mt-5 mb-5;
}

.button {
  @apply text-white;
}

@keyframes appear {
  0% {
    opacity: 0;
  }
}
</style>
