// components/combo/ComboSidebarLinks.vue
<template>
  <div class="mt-4 mb-4 w-full rounded overflow-hidden">
    <BuyComboButtons
      :cards="cards"
      :tcgplayer-price="tcgplayerPrice"
      :cardkingdom-price="cardkingdomPrice"
      class="pb-1 border-b border-light"
    />
    <div class="mt-1">
      <CopyComboLinkButton :combo-link="comboLink" />
      <ShareComboButton />
      <SimiliarCombosButton :cards="cards" :combo-id="comboId" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import CopyComboLinkButton from "@/components/combo/CopyComboLinkButton.vue";
import SimiliarCombosButton from "@/components/combo/SimiliarCombosButton.vue";
import BuyComboButtons from "@/components/combo/BuyComboButtons.vue";
import ShareComboButton from "@/components/combo/ShareComboButton.vue";

export default Vue.extend({
  components: {
    CopyComboLinkButton,
    SimiliarCombosButton,
    BuyComboButtons,
    ShareComboButton,
  },
  props: {
    cards: {
      type: Array as PropType<string[]>,
      default() {
        return [];
      },
    },
    comboLink: {
      type: String,
      default: "",
    },
    comboId: {
      type: String,
      default: "",
    },
    tcgplayerPrice: {
      type: String,
      default: "",
    },
    cardkingdomPrice: {
      type: String,
      default: "",
    },
  },
});
</script>

// frontend/components/combo/ComboSidebarLinks/ComboSidebarLinks.tsx
import BuyComboButtons from "./BuyComboButtons/BuyComboButtons";
import SimilarComboButton from "./SimilarComboButton/SimilarComboButton";
import EdhrecLink from "./EdhrecLink/EdhrecLink";
import Link from "next/link";
import ShareComboButtons from "./ShareComboButtons/ShareComboButtons";

type Props = {
  cards: string[];
  comboLink: string;
  edhrecLink: string;
  comboId: string;
  tcgPlayerPrice: string;
  cardKingdomPrice: string;
};

const ComboSidebarLinks = ({
  cards,
  comboLink,
  edhrecLink,
  comboId,
  tcgPlayerPrice,
  cardKingdomPrice,
}: Props) => {
  return (
    <div className="mt-4 mb-4 w-full rounded overflow-hidden">
      <BuyComboButtons
        cards={cards}
        tcgPlayerPrice={tcgPlayerPrice}
        cardKingdomPrice={cardKingdomPrice}
      />
      <div className="mt-1">
        <SimilarComboButton cards={cards} comboId={comboId} />
        {!!edhrecLink && <EdhrecLink link={edhrecLink} />}
        <Link
          id="report-error-button"
          className="button w-full"
          href={`/report-error/?comboId=${comboId}`}
        >
          Report an Error with this Combo
        </Link>
        <ShareComboButtons comboLink={comboLink} />
      </div>
    </div>
  );
};

export default ComboSidebarLinks;
