// components/CardTooltip.vue
<template>
  <span @mousemove="mousemove" @mouseout="mouseout">
    <div v-if="hover" class="card-tooltip" :style="{ left, top }">
      <CardImage v-if="cardName" :name="cardName" :img="imgSrc" />
    </div>
    <slot />
  </span>
</template>

<script lang="ts">
import Vue from "vue";
import CardImage from "@/components/CardImage.vue";

type TooltipData = {
  hover: boolean;
  left: string;
  top: string;
};

export default Vue.extend({
  components: {
    CardImage,
  },
  props: {
    cardName: {
      type: String,
      default: "",
    },
  },
  data(): TooltipData {
    return {
      hover: false,
      left: "0px",
      top: "0px",
    };
  },
  computed: {
    imgSrc(): string {
      return `https://api.scryfall.com/cards/named?exact=${this.cardName}&format=image&version=normal`;
    },
  },
  methods: {
    mousemove(event: MouseEvent): void {
      this.hover = true;
      this.left = event.clientX + 50 + "px";
      this.top = event.clientY - 30 + "px";
    },
    mouseout(): void {
      this.hover = false;
    },
  },
});
</script>

<style scoped>
.card-tooltip {
  pointer-events: none;
  position: fixed;
  z-index: 9000000;
  border-radius: 4.75% / 3.5%;
  height: 340px;
  width: 244px;
  overflow: hidden;
}
</style>

// src/components/layout/CardTooltip/CardTooltip.tsx
import styles from "./cardTooltip.module.scss";
import { useRef } from "react";

type Props = {
  cardName?: string;
  children?: React.ReactNode;
};

const CardTooltip = ({ cardName, children }: Props) => {
  const url = cardName ? `https://api.scryfall.com/cards/named?format=image&version=normal&exact=${encodeURIComponent(cardName)}` : "";

  const divRef = useRef<HTMLDivElement>(null);

  const handleMouseMove = (e: any) => {
    if (!divRef.current) return;
    const displayOnRightSide = window.innerWidth / 2 - e.clientX > 0;
    divRef.current.style.display = "unset";
    divRef.current.style.top = e.clientY - 30 + "px";

    if (displayOnRightSide) divRef.current.style.left = e.clientX + 50 + "px";
    else divRef.current.style.left = e.clientX - 290 + "px";
  };

  const handleMouseOut = () => {
    if (divRef.current) divRef.current.style.display = "none";
  };

  return (
    <span onMouseMove={handleMouseMove} onMouseOut={handleMouseOut}>
      <div ref={divRef} className={styles.cardTooltip}>
        {!!cardName && <img src={url} alt={cardName} />}
      </div>
      {children}
    </span>
  );
};

export default CardTooltip;
