// frontend/components/layout/CardLink/CardLink.tsx
import React from "react"
import ExternalLink from "../ExternalLink/ExternalLink";
import Card from "lib/card";

type Props = {
  name: string
  children?: React.ReactNode
  className?: string
}

const CardLink: React.FC<Props> = ({name, children, className}: Props) => {
  const card = new Card(name)

  let link = ''
  const edhrecLink = card.getEdhrecLink()
  if (edhrecLink) link = edhrecLink
  else {
    let quotes = "%22"
    if (name.includes('"')) quotes = "%27"
    link = `https://scryfall.com/search?q=%21${quotes}${encodeURIComponent(name)}${quotes}`
  }

  return (
    <ExternalLink className={className} href={link}>{children}</ExternalLink>
  )
}

export default CardLink

// frontend/components/CardLink.vue
<template>
  <ExternalLink :to="link" @focus="$emit('focus')"><slot /></ExternalLink>
</template>

<script lang="ts">
import Vue from "vue";
import ExternalLink from "@/components/ExternalLink.vue";
import Card from "@/lib/api/models/card";

export default Vue.extend({
  components: {
    ExternalLink,
  },
  props: {
    name: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      card: new Card(this.name),
    };
  },
  computed: {
    link(): string {
      const edhrecLink = this.card.getEdhrecLink();

      if (edhrecLink) {
        return edhrecLink;
      }

      let quotes = "%22";

      if (this.name.includes('"')) {
        quotes = "%27";
      }

      return `https://scryfall.com/search?q=%21${quotes}${encodeURIComponent(
        this.name
      )}${quotes}`;
    },
  },
});
</script>
