// components/CardImage.vue
<template>
  <FlipperCard :flipped="loaded && readyToFlip">
    <template slot="front">
      <img class="back-card" src="~/assets/images/card-back.png" alt="" />
    </template>
    <template slot="back">
      <img class="front-card" :src="img" :alt="name" @load="onImgLoad" />
    </template>
  </FlipperCard>
</template>

<script lang="ts">
import Vue from "vue";
import FlipperCard from "@/components/FlipperCard.vue";

export default Vue.extend({
  components: {
    FlipperCard,
  },
  props: {
    img: {
      type: String,
      default: "",
    },
    name: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      loaded: false,
      readyToFlip: false,
    };
  },
  mounted() {
    setTimeout(() => {
      this.readyToFlip = true;
    }, 300);
  },
  methods: {
    onImgLoad(): void {
      this.loaded = true;
    },
  },
});
</script>

<style scoped>
.front-card {
  @apply rounded-xl;
}
</style>

// src/components/layout/CardImage/CardImage.tsx
import styles from "./cardImage.module.scss";
import FlipperCard from "../FlipperCard/FlipperCard";
import React, { useEffect, useRef, useState } from "react";
import cardBack from "assets/images/card-back.png";
import isFoolsDay from "lib/foolsDay";
import weatheredCardBack from "assets/images/weathered-card-back.png";

type Props = {
  img: string;
  name: string;
  className?: string;
};

const CardImage = ({ img, name, className }: Props) => {
  const imageRef = useRef<HTMLImageElement>(null);
  const [loaded, setLoaded] = useState(false);
  const [readyToFlip, setReadyToFlip] = useState(false);

  useEffect(() => {
    if (imageRef.current && imageRef.current.complete) setLoaded(true);
    setTimeout(() => {
      setReadyToFlip(true);
    }, 300);
  }, []);

  return (
    <FlipperCard
      className={className}
      flipped={loaded && readyToFlip}
      front={
        <img
          className={styles.frontCard}
          src={isFoolsDay() ? weatheredCardBack.src : cardBack.src}
          alt=""
        />
      }
      back={
        <img
          ref={imageRef}
          className={styles.frontCard}
          src={img}
          alt={name}
          onLoad={() => setLoaded(true)}
        />
      }
    />
  );
};

export default CardImage;
