// src/pages/featured.tsx
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import ArtCircle from "../components/layout/ArtCircle/ArtCircle";
import ComboResults from "../components/search/ComboResults/ComboResults";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";
import {GetServerSideProps} from "next";
import {RequestService} from "../services/request.service";
import {PaginatedResponse} from "../types/api";
import {Variant} from "../lib/types";

type Props = {
  combos: Variant[];
};

const Featured = ({ combos }: Props) => {

  return (
    <PageWrapper>
      <SpellbookHead
        title="Commander Spellbook: Featured Combos"
        description="The newest featured EDH combos on Commander Spellbook."
      />
      <div className="static-page">
        <ArtCircle
          cardName="Thespian's Stage"
          className="m-auto md:block hidden"
        />
        <h1 className="heading-title">Featured Combos</h1>
        <div className="container sm:flex flex-row">
          {!!combos.length ? (
            <div className="w-full">
              <ComboResults results={combos} />
            </div>
          ) : (
            <div>
              <p>No featured combos at this time!</p>
            </div>
          )}
        </div>
      </div>
    </PageWrapper>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const requestService = new RequestService(context)
  const results = await requestService.get<PaginatedResponse<Variant>>(`${process.env.NEXT_PUBLIC_EDITOR_BACKEND_URL}/variants/?q=is:featured`)
  const backendCombos = results ? results.results : []
  return {
    props: {
      combos: backendCombos,
    }
  }
}

export default Featured;

// frontend/pages/featured.vue
<template>
  <div class="static-page">
    <ArtCircle card-name="Thespian's Stage" artist="John Avon" class="m-auto md:block hidden" />
    <h1 class="heading-title">Featured Combos</h1>

    <div class="container sm:flex flex-row">
      <div v-if="combos.length > 0" class="w-full">
        <ComboResults :results="combos" />
      </div>
      <div v-else>
        <p>No Featured combos at this time!</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import ComboResults from "@/components/search/ComboResults.vue";
import ArtCircle from "@/components/ArtCircle.vue";
import getFeaturedCombos from "@/lib/api/get-featured-combos";
import { FormattedApiResponse } from "@/lib/api/types";

type Data = {
  combos: FormattedApiResponse[];
};

export default Vue.extend({
  name: "FeaturedPage",
  components: {
    ArtCircle,
    ComboResults,
  },
  async asyncData(): Promise<Data> {
    const featuredCombos = await getFeaturedCombos();

    return {
      combos: featuredCombos,
    };
  },
  data(): Data {
    return {
      combos: [],
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Featured Combos",
    }
  },
});
</script>

<style scoped>
/* Styles here */
</style>
