// frontend/pages/find-my-combos.tsx
import {ChangeEventHandler, useEffect, useState} from "react"
import pluralize from "pluralize";
import {ColorIdentityColors, FormattedApiResponse} from "../lib/types";
import {convertDecklistToDeck, findCombosFromDecklist} from "../lib/decklist-parser";
import debounce from 'debounce'
import styles from './find-my-combos.module.scss'
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import ArtCircle from "../components/layout/ArtCircle/ArtCircle";
import ComboResults from "../components/search/ComboResults/ComboResults";
import ColorIdentityPicker from "../components/layout/ColorIdentityPicker/ColorIdentityPicker";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";

const LOCAL_STORAGE_DECK_STORAGE_KEY =
  "commander-spellbook-combo-finder-last-decklist"

const FindMyCombos = () => {

  const [decklist, setDecklist] = useState<string>('')
  const [numberOfCardsInDeck, setNumberOfCardsInDeck] = useState<number>(0)
  const [lookupInProgress, setLookupInProgress] = useState<boolean>(false)
  const [combosInDeck, setCombosInDeck] = useState<Array<FormattedApiResponse>>([])
  const [potentialCombos, setPotentialCombos] = useState<Array<FormattedApiResponse>>([])
  const [missingDeckListCards, setMissingDeckListCards] = useState<Array<any>>([])
  const [potentialCombosColorIdentity, setPotentialCombosColorIdentity] = useState<Array<ColorIdentityColors>>(['w', 'u', 'b', 'r', 'g'])
  const [deckColorIdentity, setDeckColorIdentity] = useState<Array<ColorIdentityColors>>([])

  const numberOfCardsText = `${numberOfCardsInDeck} ${pluralize("card", numberOfCardsInDeck)}`

  const numOfCombos = combosInDeck.length
  const combosInDeckHeadingText = !numOfCombos ? 'No combos found' : `${numOfCombos} ${pluralize("Combo", numOfCombos)} Found`

  const numPotentialCombos = potentialCombos.length
  const potentialCombosInDeckHeadingText = `${numPotentialCombos} Potential ${pluralize("Combo", numPotentialCombos)} Found`


  const potentialCombosMatchingDeckColorIdentity = potentialCombos.filter((combo) => combo.colorIdentity.isWithin(deckColorIdentity))
  const potentialCombosOutsideDeckColorIdentity = potentialCombos.filter((combo) => !combo.colorIdentity.isWithin(deckColorIdentity))

  const potentialCombosOutsideDeckColorIdentityFilteredByPicker = potentialCombosOutsideDeckColorIdentity.filter((combo) => combo.colorIdentity.isWithin(potentialCombosColorIdentity))
  const potentialCombosMatchingColorIdentityPicker = potentialCombos.filter((combo) => combo.colorIdentity.isWithin(potentialCombosColorIdentity))

  const numbInAdditionalColors = potentialCombosOutsideDeckColorIdentity.length
  const potentialCombosInAdditionalColorsHeadingText = `${numbInAdditionalColors} Potential ${pluralize("Combo", numbInAdditionalColors)} Found With Additional Color Requirements`


  const lookupCombos = async (newDeckList: string) => {
    setLookupInProgress(true)
    const deck = await convertDecklistToDeck(newDeckList)
    setNumberOfCardsInDeck(deck.numberOfCards)

    setCombosInDeck([])
    setPotentialCombos([])
    setMissingDeckListCards([])
    setPotentialCombosColorIdentity(['w', 'u', 'b', 'r', 'g'])
    setDeckColorIdentity(deck.colorIdentity)

    if (deck.numberOfCards < 2) return setLookupInProgress(false)

    localStorage.setItem(LOCAL_STORAGE_DECK_STORAGE_KEY, newDeckList)

    const combos = await findCombosFromDecklist(deck.cards)

    setCombosInDeck(combos.combosInDecklist)
    setPotentialCombos(combos.potentialCombos)
    setMissingDeckListCards(combos.missingCardsForPotentialCombos)

    setLookupInProgress(false)
  }

  const clearDecklist = () => {
    setDecklist('')
    setCombosInDeck([])
    setPotentialCombos([])
    localStorage.removeItem(LOCAL_STORAGE_DECK_STORAGE_KEY)
  }

  useEffect(() => {
    const savedDeck = localStorage.getItem(LOCAL_STORAGE_DECK_STORAGE_KEY)

    if (!savedDeck?.trim()) return

    setDecklist(savedDeck)
    lookupCombos(savedDeck)
  }, [])

  const debouncedLookupCombos = debounce(lookupCombos, 1000)
  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setDecklist(e.target.value)
    debouncedLookupCombos(e.target.value)
  }

  return (
    <PageWrapper>
      <SpellbookHead title="Commander Spellbook: Find My Combos" description="Input a decklist to generate all possible combos in your deck as well as combo suggestions." />
      <div className={`${styles.findMyCombosContainer} static-page`}>
        <ArtCircle cardName="Exploration" className="m-auto md:block hidden"/>
        <h1 className="heading-title text-center">Find My Combos</h1>
        <h2 className="heading-subtitle text-center mt-0">
          Uncover combos in your deck, and discover potential combos.
        </h2>
        <label htmlFor="decklist-input" className="sr-only">
          Copy and paste your decklist into the text box to discover the combos in
          your deck.
        </label>
        <section>

          <textarea
            id="decklist-input"
            className={styles.decklistInput}
            value={decklist}
            placeholder={`Supported decklist formats:
              Ancient Tomb
              1 Ancient Tomb
              1x Ancient Tomb
              Ancient Tomb (uma) 236
              `}
            onChange={handleInput}
          />

          {!!decklist && (
            <>
              <span id="decklist-card-count" className={`${styles.decklistCardCount} gradient relative`} aria-hidden="true">
                {numberOfCardsText}
              </span>
              <button id="clear-decklist-input" className={`${styles.clearDecklistInput} button`} onClick={clearDecklist}>
                Clear Decklist
              </button>
            </>
          )}

          {!decklist && (
            <div id="decklist-hint" className={`${styles.decklistHint} heading-subtitle`} aria-hidden="true">
              Paste your decklist
            </div>
          )}
        </section>

        <div id="decklist-app" className={styles.decklistApp}>
          {lookupInProgress && (
            <section>
              <h2 className="heading-subtitle">Loading Combos...</h2>
            </section>
          )}

          {!lookupInProgress && decklist && (
            <section id="combos-in-deck-section">
              <h2 className="heading-subtitle">{combosInDeckHeadingText}</h2>
              <ComboResults results={combosInDeck} />
            </section>
          )}

          {!lookupInProgress && !!potentialCombosMatchingDeckColorIdentity.length && (
            <section id="potential-combos-in-deck-section">
              <h2 className="heading-subtitle">{potentialCombosInDeckHeadingText}</h2>
              <p>List of combos where your decklist is missing 1 combo piece.</p>
              <ComboResults results={potentialCombosMatchingDeckColorIdentity} missingDecklistCards={missingDeckListCards}/>
            </section>
          )}

          {!lookupInProgress && !!potentialCombosOutsideDeckColorIdentity.length && (
            <section id="potential-combos-outside-color-identity-section">
              <h2 className="heading-subtitle">{potentialCombosInAdditionalColorsHeadingText}</h2>
              <p>
                List of combos where your decklist is missing 1 combo piece, but
                requires at least one additional color. Toggle the color symbols to
                filter for identity.
              </p>
              <ColorIdentityPicker onChange={setPotentialCombosColorIdentity} chosenColors={potentialCombosColorIdentity} />
              <ComboResults results={potentialCombosOutsideDeckColorIdentity} missingDecklistCards={missingDeckListCards}/>
              {!potentialCombosOutsideDeckColorIdentityFilteredByPicker.length && (
                <h2 className="heading-subtitle">
                  No Combos Found Matching the Selected Color Identity
                </h2>
              )}
            </section>
          )}


        </div>
      </div>
    </PageWrapper>
  )
}

export default FindMyCombos

// frontend/pages/find-my-combos.vue
<template>
  <div class="static-page">
    <ArtCircle card-name="Exploration" artist="Florian de Gesincourt" class="m-auto md:block hidden" />
    <h1 class="heading-title text-center">Find My Combos</h1>
    <h2 class="heading-subtitle text-center mt-0">
      Uncover combos in your deck, and discover potential combos.
    </h2>

    <label for="decklist-input" class="sr-only">Copy and paste your decklist into the text box to discover the combos in
      your deck.</label>

    <section>
      <textarea id="decklist-input" v-model="decklist" placeholder="Supported decklist formats:
Ancient Tomb
1 Ancient Tomb
1x Ancient Tomb
Ancient Tomb (uma) 236
" @input="onInput">
      </textarea>

      <span v-if="decklist" id="decklist-card-count" class="gradient" aria-hidden="true">{{
        numberOfCardsText
      }}</span>
      <button v-if="decklist" id="clear-decklist-input" class="button" @click="clearDecklist">
        Clear Decklist
      </button>

      <div v-if="!decklist" id="decklist-hint" class="heading-subtitle" aria-hidden="true">
        Paste your decklist
      </div>
    </section>

    <div id="decklist-app">
      <section v-if="lookupInProgress">
        <h2 class="heading-subtitle">Loading Combos...</h2>
      </section>

      <section v-if="!lookupInProgress && decklist" id="combos-in-deck-section">
        <h2 class="heading-subtitle">{{ combosInDeckHeadingText }}</h2>

        <ComboResults :results="combosInDeck" />
      </section>

      <section v-if="!lookupInProgress && potentialCombosMatchingDeckColorIdentity.length > 0"
        id="potential-combos-in-deck-section">
        <h2 class="heading-subtitle">{{ potentialCombosInDeckHeadingText }}</h2>
        <p>
          List of combos where your decklist is missing 1 combo piece.
        </p>

        <ComboResults :results="potentialCombosMatchingDeckColorIdentity"
          :missing-decklist-cards="missingDecklistCards" />
      </section>

      <section v-if="!lookupInProgress && potentialCombosOutsideDeckColorIdentity.length > 0"
        id="potential-combos-outside-color-identity-section">
        <h2 class="heading-subtitle">{{ potentialCombosInAdditionalColorsHeadingText }}</h2>
        <p>
          List of combos where your decklist is missing 1 combo piece, but requires at least one additional color.
          Toggle the
          color symbols to filter for identity.
        </p>

        <ColorIdentityPicker v-model="potentialCombosColorIdentity" class="mb-4"
          :chosen-colors="potentialCombosColorIdentity" />

        <ComboResults :results="potentialCombosOutsideDeckColorIdentityFilteredByPicker"
          :missing-decklist-cards="missingDecklistCards" />
        <h2 v-if="potentialCombosOutsideDeckColorIdentityFilteredByPicker.length === 0" class="heading-subtitle">No
          Combos Found Matching the Selected Color Identity</h2>
      </section>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
// eslint-disable-next-line import/no-named-as-default
import debounce from "debounce";
import ArtCircle from "@/components/ArtCircle.vue";
import ComboResults from "@/components/search/ComboResults.vue";
import ColorIdentityPicker from "@/components/ColorIdentityPicker.vue";
import {
  findCombosFromDecklist,
  convertDecklistToDeck,
} from "@/lib/decklist-parser";

import type { FormattedApiResponse, ColorIdentityColors } from "@/lib/api/types";
import type Card from "@/lib/api/models/card";

type ComboFinderData = {
  decklist: string;
  numberOfCardsInDeck: number;
  lookupInProgress: boolean;
  combosInDeck: FormattedApiResponse[];
  potentialCombos: FormattedApiResponse[];
  missingDecklistCards: Card[];
  potentialCombosColorIdentity: ColorIdentityColors[];
  deckColorIdentity: ColorIdentityColors[];
};

const LOCAL_STORAGE_DECK_STORAGE_KEY =
  "commander-spellbook-combo-finder-last-decklist";

export default Vue.extend({
  components: {
    ArtCircle,
    ComboResults,
    ColorIdentityPicker,
  },
  data(): ComboFinderData {
    return {
      decklist: "",
      numberOfCardsInDeck: 0,
      lookupInProgress: false,
      combosInDeck: [],
      potentialCombos: [],
      missingDecklistCards: [],
      potentialCombosColorIdentity: ["w", "u", "b", "r", "g"],
      deckColorIdentity: [],
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Find My Combos",
    }
  },
  computed: {
    numberOfCardsText(): string {
      return `${this.numberOfCardsInDeck} ${this.$pluralize(
        "card",
        this.numberOfCardsInDeck
      )}`;
    },
    combosInDeckHeadingText(): string {
      const numOfCombos = this.combosInDeck.length;

      if (numOfCombos === 0) {
        return "No Combos Found";
      }

      return `${numOfCombos} ${this.$pluralize("Combo", numOfCombos)} Found`;
    },
    potentialCombosInDeckHeadingText(): string {
      const numOfCombos = this.potentialCombosMatchingDeckColorIdentity.length;

      return `${numOfCombos} Potential ${this.$pluralize(
        "Combo",
        numOfCombos
      )} Found`;
    },
    potentialCombosInAdditionalColorsHeadingText(): string {
      const numOfCombos = this.potentialCombosOutsideDeckColorIdentity.length;

      return `${numOfCombos} Potential ${this.$pluralize(
        "Combo",
        numOfCombos
      )} Found With Additional Color Requirements`;
    },
    potentialCombosMatchingDeckColorIdentity(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return combo.colorIdentity.isWithin(this.deckColorIdentity);
      });
    },
    potentialCombosOutsideDeckColorIdentity(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return !combo.colorIdentity.isWithin(this.deckColorIdentity);
      });
    },
    potentialCombosOutsideDeckColorIdentityFilteredByPicker(): FormattedApiResponse[] {
      return this.potentialCombosOutsideDeckColorIdentity.filter((combo) => {
        return combo.colorIdentity.isWithin(this.potentialCombosColorIdentity);
      })
    },
    potentialCombosMatchingColorIdentityPicker(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return combo.colorIdentity.isWithin(this.potentialCombosColorIdentity);
      });
    }
  },
  mounted() {
    const savedDeck = localStorage.getItem(LOCAL_STORAGE_DECK_STORAGE_KEY);

    if (savedDeck?.trim()) {
      this.decklist = savedDeck;
      this.lookupCombos();
    }
  },
  methods: {
    onInput: debounce(function () {
      // @ts-ignore
      this.lookupCombos();
    }, 1000),
    async lookupCombos() {
      this.lookupInProgress = true;

      const deck = await convertDecklistToDeck(this.decklist);
      this.numberOfCardsInDeck = deck.numberOfCards;

      this.combosInDeck = [];
      this.potentialCombos = [];
      this.missingDecklistCards = [];
      this.potentialCombosColorIdentity = ["w", "u", "b", "r", "g"];
      this.deckColorIdentity = deck.colorIdentity;

      // not possible to have any combos if deck has 1
      // or fewer card in it, so we can skip the lookup
      if (this.numberOfCardsInDeck < 2) {
        this.lookupInProgress = false;
        return;
      }

      localStorage.setItem(LOCAL_STORAGE_DECK_STORAGE_KEY, this.decklist);

      // TODO: let's debounce in case some weirdo is manually
      // typing in their deck list
      const combos = await findCombosFromDecklist(deck.cards);

      this.combosInDeck = combos.combosInDecklist;
      this.potentialCombos = combos.potentialCombos;
      this.missingDecklistCards = combos.missingCardsForPotentialCombos;

      this.lookupInProgress = false;
    },

    clearDecklist() {
      this.decklist = "";
      this.combosInDeck = [];
      this.potentialCombos = [];
      localStorage.removeItem(LOCAL_STORAGE_DECK_STORAGE_KEY);
    },
  },
});
</script>

<style scoped>
p {
  @apply my-4;
}

section {
  @apply flex flex-col items-center justify-center py-4;
}

#decklist-input {
  @apply h-80 w-full py-2 px-4 pb-6 mt-4 border-2 border-dark resize-none;
}

#decklist-input:active {
  @apply border-primary;
}

#decklist-input:focus {
  @apply border-primary;
}

#clear-decklist-input {
  @apply cursor-pointer;
}

#decklist-card-count {
  @apply border-2 border-dark w-1/3 text-center py-2 -mt-4;
}

#decklist-app {
  @apply py-4;
}

#decklist-hint {
  @apply flex relative text-center items-center justify-center flex-col -my-10 mb-8;
}

#decklist-hint::before {
  content: "";
  height: 90px;
  width: 20px;
  background-image: url("~assets/svgs/combo-finder-arrow-hint.svg");

  @apply block bg-center bg-no-repeat bg-contain;
}

@media (min-width: 768px) {
  #decklist-input {
    @apply w-2/3;
  }
}
</style>
