// pages/index.vue
<template>
  <div class="container relative md:h-screen z-10">
    <div class="w-full">
      <Logo />

      <h2 class="font-title my-1 sm:my-3 text-2xl sm:text-3xl md:text-4xl">
        The Search Engine for EDH Combos
      </h2>

      <SearchBar :on-home-page="true" class="bg-white mt-4 md:w-2/3 h-20" />

      <div class="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
        <nuxt-link to="/advanced-search/" class="button md:m-1">
          Advanced Search
        </nuxt-link>
        <nuxt-link to="/syntax-guide/" class="button md:m-1">
          Syntax Guide
        </nuxt-link>
        <RandomButton :query="query" class="random-button button md:m-1">
          Random Combo
        </RandomButton>
        <nuxt-link to="/featured/" class="previwed-combos-button button md:m-1">
          Crimson Vow Combos
        </nuxt-link>
      </div>

      <div class="button-links flex md:w-2/3 m-auto">
        <ExternalLink
          class="button"
          to="https://www.patreon.com/commanderspellbook"
          >Join our Patreon</ExternalLink
        >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import RandomButton from "@/components/RandomButton.vue";
import SearchBar from "@/components/SearchBar.vue";
import ExternalLink from "@/components/ExternalLink.vue";
import Logo from "@/components/Logo.vue";

export default Vue.extend({
  components: {
    ExternalLink,
    RandomButton,
    SearchBar,
    Logo,
  },
  layout: "landing",
  computed: {
    query(): string {
      return this.$store.state.query.value;
    },
  },
  mounted() {
    const query = this.$route.query.q;
    const { status, id } = this.$route.query;

    if (Number(query) > 0 || Number(id) > 0) {
      this.$router.push(`/combo/${id || query}/`);
      return;
    }

    if (query === "spoiled" || status === "spoiled") {
      this.$router.push("/search/?q=is:previewed");
      return;
    }

    if (query === "banned" || status === "banned") {
      this.$router.push("/search/?q=is:banned");
      return;
    }

    if (!(typeof query === "string")) {
      return;
    }

    this.$router.push(`/search/?q=${query}`);
  },
});
</script>

<style scoped>
.container {
  @apply flex flex-col items-center justify-center text-center m-auto;
}

.button {
  @apply bg-dark text-white mx-0 mt-2 mb-0 flex-grow border-dark;
}

.button:hover {
  @apply bg-transparent text-dark;
}

@media (min-width: 768px) {
  .button {
    @apply ml-2;
  }

  .button:first-child {
    @apply ml-0;
  }
}
</style>

// frontend/pages/index.tsx
import Head from 'next/head'
import Link from "next/link"
import Footer from "../components/layout/Footer/Footer";
import SearchBar from "../components/SearchBar/SearchBar";
import styles from './index.module.scss'
import SpellbookLogo from "../components/layout/SpellbookLogo/SpellbookLogo";
import RandomButton from "../components/RandomButton/RandomButton";
import {useRouter} from "next/router";
import {useEffect} from "react";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";


export default function Home() {

  const router = useRouter()
  const query = router.query.q ? `${router.query.q}` : ``

  useEffect(() => {
    const { status, id } = router.query;

    if (Number(query) > 0 || Number(id) > 0) {
      router.push(`/combo/${id || query}/`);
      return
    }

    if (query === "spoiled" || status === "spoiled") {
      router.push("/search/?q=is:previewed");
      return
    }


    if (query === "banned" || status === "banned") {
      router.push("/search/?q=is:banned");
      return
    }


    if (!query) return

    router.push(`/search/?q=${query}`)
  }, [])

  return (
    <>
      <SpellbookHead title="Commander Spellbook: The Search Engine for EDH Combos" description="The Premier Magic: the Gathering Combo Search Engine for the Commander / Elder Dragon Highlander (EDH) Format."/>
      <main>
        <div className="gradient">
          <div className={`container ${styles.container} relative md:h-screen z-10`}>
            <div className="w-full">
              <SpellbookLogo/>

              <h2 className="font-title my-1 sm:my-3 text-2xl sm:text-3xl md:text-4xl">
                The Search Engine for EDH Combos
              </h2>

              <SearchBar onHomepage className="bg-white mt-4 md:w-2/3 h-20"/>

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link href="/advanced-search/" className={`dark ${styles.button} button md:m-1`}>
                  Advanced Search
                </Link>
                <Link href="/syntax-guide/" className={`dark ${styles.button} button md:m-1`}>
                  Syntax Guide
                </Link>
                  <RandomButton query={query} className={`${styles.button} dark button md:m-1`}>
                    Random Combo
                  </RandomButton>
              </div>

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link href="/find-my-combos/" className={`dark ${styles.button} button md:m-1`}>
                  Find My Combos
                </Link>
                <Link v-if="featuredComboButtonText" id="featured-combos-button" href="/featured/"
                      className={`previwed-combos-button dark ${styles.button} button md:m-1`}>
                  Featured Combos
                </Link>
              </div>
            </div>
        </div>
          <Footer/>
      </div>
      </main>

    </>
  )
}
