// frontend/pages/index.vue
<template>
  <div class="container relative md:h-screen z-10">
    <div class="w-full">
      <SpellbookLogo />

      <h2 class="font-title my-1 sm:my-3 text-2xl sm:text-3xl md:text-4xl">
        The Search Engine for EDH Combos
      </h2>

      <SearchBar :on-home-page="true" class="bg-white mt-4 md:w-2/3 h-20" />

      <div class="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
        <nuxt-link to="/advanced-search/" class="dark button md:m-1">
          Advanced Search
        </nuxt-link>
        <nuxt-link to="/syntax-guide/" class="dark button md:m-1">
          Syntax Guide
        </nuxt-link>
        <RandomButton :query="query" class="random-button dark button md:m-1">
          Random Combo
        </RandomButton>
      </div>

      <div class="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
        <nuxt-link to="/find-my-combos/" class="dark button md:m-1">
          Find My Combos
        </nuxt-link>
        <nuxt-link
          v-if="featuredComboButtonText"
          id="featured-combos-button"
          to="/featured/"
          class="previwed-combos-button dark button md:m-1"
        >
          {{ featuredComboButtonText }}
        </nuxt-link>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import RandomButton from "@/components/RandomButton.vue";
import SearchBar from "@/components/SearchBar.vue";
import SpellbookLogo from "@/components/SpellbookLogo.vue";

type RawPropertiesResponse = {
  results: { key: string; value: string }[];
};

function getDefaultData() {
  return {
    featuredComboButtonText: "",
  };
}

export default Vue.extend({
  name: "HomePage",
  components: {
    RandomButton,
    SearchBar,
    SpellbookLogo,
  },
  layout: "LandingLayout",
  async asyncData(context) {
    const { EDITOR_BACKEND_URL } = context.env;

    if (!EDITOR_BACKEND_URL) {
      return {
        featuredComboButtonText: "Featured Combos (Mocked Data)",
      };
    }

    try {
      const dataFromEditorBackend: RawPropertiesResponse =
        await context.$http.$get(
          `${EDITOR_BACKEND_URL}properties/?format=json`
        );
      const buttonTextData = dataFromEditorBackend.results.find((data) => {
        return data.key === "featured_combos_title";
      });

      if (!buttonTextData) {
        return getDefaultData();
      }

      return {
        featuredComboButtonText: buttonTextData.value,
      };
    } catch (_) {
      return getDefaultData();
    }
  },

  data() {
    return getDefaultData();
  },
  computed: {
    query(): string {
      return this.$store.state.query.value;
    },
  },
  mounted() {
    const query = this.$route.query.q;
    const { status, id } = this.$route.query;

    if (Number(query) > 0 || Number(id) > 0) {
      this.$router.push(`/combo/${id || query}/`);
      return;
    }

    if (query === "spoiled" || status === "spoiled") {
      this.$router.push("/search/?q=is:previewed");
      return;
    }

    if (query === "banned" || status === "banned") {
      this.$router.push("/search/?q=is:banned");
      return;
    }

    if (!(typeof query === "string")) {
      return;
    }

    this.$router.push(`/search/?q=${query}`);
  },
});
</script>

<style scoped>
.container {
  @apply flex flex-col items-center justify-center text-center m-auto;
}

.button {
  @apply mx-0 mt-2 mb-0 flex-grow;
}

.button:hover {
  @apply bg-transparent text-dark;
}

@media (min-width: 768px) {
  .button {
    @apply ml-2;
  }

  .button:first-child {
    @apply ml-0;
  }
}
</style>

// frontend/pages/index.tsx
import Head from "next/head";
import Link from "next/link";
import Footer from "../components/layout/Footer/Footer";
import SearchBar from "../components/SearchBar/SearchBar";
import styles from "./index.module.scss";
import SpellbookLogo from "../components/layout/SpellbookLogo/SpellbookLogo";
import RandomButton from "../components/RandomButton/RandomButton";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";
import AnalyticsCookieBanner from "../components/layout/AnalyticsCookieBanner/AnalyticsCookieBanner";

type Props = {
  featuredComboButtonText: string;
};

const DEFAULT_PROPS = {
  props: {
    featuredComboButtonText: "Featured Combos (Mocked Data)",
  },
};

export default function Home({ featuredComboButtonText }: Props) {
  const router = useRouter();
  const query = router.query.q ? `${router.query.q}` : ``;

  useEffect(() => {
    const { status, id } = router.query;

    if (Number(query) > 0 || Number(id) > 0) {
      router.push(`/combo/${id || query}/`);
      return;
    }

    if (query === "spoiled" || status === "spoiled") {
      router.push("/search/?q=is:previewed");
      return;
    }

    if (query === "banned" || status === "banned") {
      router.push("/search/?q=is:banned");
      return;
    }

    if (!query) return;

    router.push(`/search/?q=${query}`);
  }, []);

  return (
    <>
      <SpellbookHead
        title="Commander Spellbook: The Search Engine for EDH Combos"
        description="The Premier Magic: the Gathering Combo Search Engine for the Commander / Elder Dragon Highlander (EDH) Format."
      />
      <AnalyticsCookieBanner />
      <main>
        <div className="gradient">
          <div
            className={`container ${styles.container} relative md:h-screen z-10`}
          >
            <div className="w-full">
              <SpellbookLogo />

              <h2 className="font-title my-1 sm:my-3 text-2xl sm:text-3xl md:text-4xl">
                The Search Engine for EDH Combos
              </h2>

              <SearchBar onHomepage className="bg-white mt-4 md:w-2/3 h-20" />

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link
                  href="/advanced-search/"
                  className={`dark ${styles.button} button md:m-1`}
                >
                  Advanced Search
                </Link>
                <Link
                  href="/syntax-guide/"
                  className={`dark ${styles.button} button md:m-1`}
                >
                  Syntax Guide
                </Link>
                <RandomButton
                  query={query}
                  className={`random-button ${styles.button} dark button md:m-1`}
                >
                  Random Combo
                </RandomButton>
              </div>

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link
                  href="/find-my-combos/"
                  className={`dark ${styles.button} button md:m-1`}
                >
                  Find My Combos
                </Link>
                <Link
                  id="featured-combos-button"
                  href="/featured/"
                  className={`previwed-combos-button dark ${styles.button} button md:m-1`}
                >
                  {featuredComboButtonText}
                </Link>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  // const { EDITOR_BACKEND_URL } = process.env;
  //
  // if (!EDITOR_BACKEND_URL) {
  //   return DEFAULT_PROPS;
  // }
  //
  // const res = await fetch(`${EDITOR_BACKEND_URL}properties/?format=json`);
  // const dataFromEditorBackend = await res.json();
  // const buttonTextData = dataFromEditorBackend.results.find(
  //   (data: { key: string; value: string }) => {
  //     return data.key === "featured_combos_title";
  //   }
  // );
  //
  // if (!buttonTextData) {
  //   return DEFAULT_PROPS;
  // }

  return {
    props: {
      // featuredComboButtonText: buttonTextData.value,
      featuredComboButtonText: 'Tales of Middle-earth Combos',
    },
  };
}
