// frontend/pages/random.vue
<template>
  <SplashPage title="Randomizing"
    flavor="Ever try to count hyperactive schoolchildren while someone shouts random numbers in your ear? It’s like that."
    art-circle-card-name="Chaosphere" art-circle-artist-name="Steve Luke" />
</template>

<script lang="ts">
import Vue from "vue";
import SplashPage from "@/components/SplashPage.vue";
import random from "@/lib/api/random";

export default Vue.extend({
  name: "RandomPage",
  components: {
    SplashPage,
  },
  layout: "SplashLayout",
  head() {
    return {
      title: "Commander Spellbook: Random",
    }
  },

  async mounted(): Promise<void> {
    let query = this.$route.query.q;
    if (typeof query !== "string") {
      query = "";
    }
    const router = this.$router;

    try {
      const randomCombo = await random(query);
      const params: Parameters<typeof router.replace>[0] = {
        path: `/combo/${randomCombo.commanderSpellbookId}/`,
      };

      if (query) {
        params.query = { q: query };
      }

      router.replace(params);
    } catch (err) {
      router.replace({ path: "/combo-not-found/" });
    }
  },
});
</script>

// frontend/pages/random.tsx
import SplashPage from "../components/layout/SplashPage/SplashPage";
import { useEffect } from "react";
import random from "../lib/random";
import { useRouter } from "next/router";
import { Url } from "url";
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";

const Random = () => {
  const router = useRouter();

  useEffect(() => {
    let query = router.query.q;
    if (typeof query !== "string") query = "";

    random(query)
      .then((combo) => {
        const url: Partial<Url> = {
          pathname: `/combo/${combo.commanderSpellbookId}`,
        };
        if (query) url.query = `${query}`;
        router.replace(url);
      })
      .catch(() => {
        router.replace("/combo-not-found");
      });
  }, []);

  return (
    <PageWrapper>
      <SpellbookHead
        title="Commander Spellbook: Random"
        description="Find a random EDH combo on Commander Spellbook."
      />
      <SplashPage
        title="Randomizing"
        flavor="Ever try to count hyperactive schoolchildren while someone shouts random numbers in your ear? It’s like that."
        artCircleCardName="Chaosphere"
        pulse
      >
        <p>Random combo</p>
      </SplashPage>
    </PageWrapper>
  );
};

export default Random;
