// pages/random.vue
<template>
  <SplashPage
    title="Randomizing"
    flavor="Ever try to count hyperactive schoolchildren while someone shouts random numbers in your ear? It’s like that."
    art-circle-card-name="Chaosphere"
    art-circle-artist-name="Steve Luke"
  />
</template>

<script lang="ts">
import Vue from "vue";
import SplashPage from "@/components/SplashPage.vue";
import spellbookApi from "commander-spellbook";

export default Vue.extend({
  components: {
    SplashPage,
  },
  layout: "splash",

  async mounted(): Promise<void> {
    const randomCombo = await spellbookApi.random();

    this.$router.replace({
      path: `/combo/${randomCombo.commanderSpellbookId}`,
    });
  },
});
</script>

// frontend/pages/random.tsx
import SplashPage from "../components/layout/SplashPage/SplashPage";
import { useEffect } from "react";
import random from "../lib/random";
import { useRouter } from "next/router";
import { Url } from "url";
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";

const Random = () => {
  const router = useRouter();

  useEffect(() => {
    let query = router.query.q;
    if (typeof query !== "string") query = "";

    random(query)
      .then((combo) => {
        const url: Partial<Url> = {
          pathname: `/combo/${combo.commanderSpellbookId}`,
        };
        if (query) url.query = `${query}`;
        router.replace(url);
      })
      .catch(() => {
        router.replace("/combo-not-found");
      });
  }, []);

  return (
    <PageWrapper>
      <SpellbookHead
        title="Commander Spellbook: Random"
        description="Find a random EDH combo on Commander Spellbook."
      />
      <SplashPage
        title="Randomizing"
        flavor="Ever try to count hyperactive schoolchildren while someone shouts random numbers in your ear? It’s like that."
        artCircleCardName="Chaosphere"
        pulse
      >
        <p>Random combo</p>
      </SplashPage>
    </PageWrapper>
  );
};

export default Random;
