// frontend/pages/search.tsx
import React, { useEffect, useState } from "react";
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import SearchMessage from "../components/search/SearchMessage/SearchMessage";
import StyledSelect, {
  Option,
} from "../components/layout/StyledSelect/StyledSelect";
import { useRouter } from "next/router";
import search from "../lib/search";
import { SearchResults } from "../lib/types";
import { DEFAULT_ORDER, DEFAULT_SORT, DEFAULT_VENDOR } from "../lib/constants";
import SearchPagination from "../components/search/SearchPagination/SearchPagination";
import ComboResults from "../components/search/ComboResults/ComboResults";
import NoCombosFound from "../components/layout/NoCombosFound/NoCombosFound";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";

type Props = {};

export type SearchResultsState = Omit<SearchResults, "errors"> & {
  errors: string;
  page: number;
  maxNumberOfCombosPerPage: number;
};

const SORT_OPTIONS: Option[] = [
  { value: "popularity", label: "Popularity" },
  { value: "colors", label: "Color Identity" },
  { value: "price", label: "Price" },
  {
    value: "cards",
    label: "# of Cards",
  },
  {
    value: "prerequisites",
    label: "# of Prerequisites",
  },
  {
    value: "steps",
    label: "# of Steps",
  },
];

const ORDER_OPTIONS: Option[] = [
  { value: "auto", label: "Auto" },
  { value: "asc", label: "Ascending" },
  { value: "desc", label: "Descending" },
];

const Search: React.FC<Props> = ({}: Props) => {
  const [loaded, setLoaded] = useState(false);
  const [redirecting, setRedirecting] = useState(false);

  const [results, setResults] = useState<SearchResultsState>({
    combos: [],
    message: "",
    errors: "",
    page: 1,
    vendor: DEFAULT_VENDOR,
    order: DEFAULT_ORDER,
    sort: DEFAULT_SORT,
    maxNumberOfCombosPerPage: 78,
  });
  const {
    combos,
    message,
    vendor,
    order,
    sort,
    page,
    maxNumberOfCombosPerPage,
  } = results;

  const router = useRouter();

  const parseSearchQuery = () => {
    const query = router.query.q;

    if (!query || typeof query !== "string") return "";

    return query;
  };

  const updateSearchResults = async (query: string) => {
    const newResults = await search(query);

    if (newResults.combos.length === 1) {
      setRedirecting(true);
      router.replace({
        pathname: `/combo/${newResults.combos[0].commanderSpellbookId}/`,
        query: { q: query },
      });
      return;
    }
    setLoaded(true);
    setResults({
      ...newResults,
      page: 1,
      errors: newResults.errors.join(" "),
      maxNumberOfCombosPerPage: 78,
    });
  };

  useEffect(() => {
    setLoaded(false);
    updateSearchResults(parseSearchQuery());
  }, [router.query.q]);

  const totalResults = combos.length;
  const totalPages = Math.floor(totalResults / maxNumberOfCombosPerPage) + 1;

  const startingPoint =
    page > totalPages
      ? (totalPages - 1) * maxNumberOfCombosPerPage
      : (page - 1) * maxNumberOfCombosPerPage;

  const paginatedResults =
    totalResults > maxNumberOfCombosPerPage
      ? combos.slice(startingPoint, startingPoint + maxNumberOfCombosPerPage)
      : combos;

  const firstResult =
    page * maxNumberOfCombosPerPage - maxNumberOfCombosPerPage + 1;
  const lastResult = Math.min(
    firstResult + maxNumberOfCombosPerPage - 1,
    totalResults
  );

  const goForward = () => {
    setResults({
      ...results,
      page: Math.min(page + 1, totalPages),
    });
  };

  const goBack = () => {
    setResults({ ...results, page: Math.max(page - 1, 1) });
  };

  const handleSortChange = (value: string) => {
    const query = String(router.query.q)
      .replace(/((\s)?sort(:|=)\w*|$)/, ` sort:${value}`)
      .trim();
    router.push({ pathname: "/search/", query: { q: query, page: "1" } });
  };

  const handleOrderChange = (value: string) => {
    const query = String(router.query.q)
      .replace(/((\s)?order(:|=)\w*|$)/, ` order:${value}`)
      .trim();
    router.push({ pathname: "/search/", query: { q: query, page: "1" } });
  };

  return (
    <PageWrapper>
      <SpellbookHead
        title="Commander Spellbook: Search Results"
        description="Search results for all EDH combos matching your query."
      />
      <div>
        <h1 className="sr-only">Search Results</h1>

        <SearchMessage
          message={results.message}
          errors={results.errors}
          currentPage={results.page}
          totalPages={1}
          totalResults={1}
          maxNumberOfCombosPerPage={1}
        />

        {paginatedResults.length > 0 && (
          <div className="border-b border-light">
            <div className="container sm:flex flex-row items-center justify-center">
              <div className="mr-2 sm:mt-0 mt-2" aria-hidden="true">
                Sorted by
              </div>
              <StyledSelect
                value={sort}
                id="sort-combos-select"
                onChange={handleSortChange}
                selectBackgroundClassName="border-dark border-2 my-2 sm:mr-2"
                selectTextClassName="text-dark"
                label="Change how combos are sorted"
                options={SORT_OPTIONS}
              />
              <div className="mx-1 hidden sm:block" aria-hidden="true">
                :
              </div>
              <StyledSelect
                id="order-combos-select"
                value={order}
                onChange={handleOrderChange}
                selectBackgroundClassName="border-dark border-2 sm:m-2"
                selectTextClassName="text-dark"
                label="Change sort direction, ascending or descending"
                options={ORDER_OPTIONS}
              />
              <div className="flex-grow" />
              <SearchPagination
                currentPage={page}
                totalPages={totalPages}
                aria-hidden="true"
                onGoForward={goForward}
                onGoBack={goBack}
              />
            </div>
          </div>
        )}

        <div className="container sm:flex flex-row">
          {paginatedResults.length > 0 ? (
            <div className="w-full">
              <ComboResults
                results={results}
                paginatedResults={paginatedResults}
              />

              <SearchPagination
                currentPage={page}
                totalPages={totalPages}
                aria-hidden="true"
                onGoForward={goForward}
                onGoBack={goBack}
              />
            </div>
          ) : (
            <NoCombosFound loaded={false} />
          )}
        </div>
      </div>
    </PageWrapper>
  );
};

export default Search;

// frontend/pages/search.vue
<template>
  <div>
    <h1 class="sr-only">Search Results</h1>

    <SearchMessage :message="message" :errors="errors" :current-page="page" :total-pages="totalPages"
      :max-number-of-combos-per-page="maxNumberOfCombosPerPage" :total-results="totalResults" />

    <div v-if="paginatedResults.length > 0" class="border-b border-light">
      <div class="container sm:flex flex-row items-center justify-center">
        <div class="mr-2 sm:mt-0 mt-2" aria-hidden="true">Sorted by</div>
        <StyledSelect id="sort-combos-select" v-model="sort" class="my-2 sm:mr-2"
          select-background-class="border-dark border-2" select-text-class="text-dark"
          label="Change how combos are sorted" :options="sortOptions" />
        <div class="mx-1 hidden sm:block" aria-hidden="true">:</div>
        <StyledSelect id="order-combos-select" v-model="order" class="sm:m-2"
          select-background-class="border-dark border-2" select-text-class="text-dark"
          label="Change sort direction, ascending or descending" :options="orderOptions" />
        <div class="flex-grow"></div>
        <SearchPagination :current-page="page" :total-pages="totalPages" aria-hidden="true" @go-forward="goForward"
          @go-back="goBack" />
      </div>
    </div>

    <div class="container sm:flex flex-row">
      <div v-if="paginatedResults.length > 0" class="w-full">
        <ComboResults :results="paginatedResults" :sort="sort" :vendor="vendor" />

        <SearchPagination :current-page="page" :total-pages="totalPages" @go-forward="goForward" @go-back="goBack" />
      </div>

      <NoCombosFound v-else :loaded="loaded && !redirecting" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import ComboResults from "@/components/search/ComboResults.vue";
import NoCombosFound from "@/components/search/NoCombosFound.vue";
import SearchPagination from "@/components/search/SearchPagination.vue";
import SearchMessage from "@/components/search/SearchMessage.vue";
import StyledSelect, { Option } from "@/components/StyledSelect.vue";
import search from "@/lib/api/search";
import { DEFAULT_ORDER, DEFAULT_SORT, DEFAULT_VENDOR } from "@/lib/constants";

import type {
  FormattedApiResponse,
  SortValue,
  OrderValue,
  VendorValue,
} from "@/lib/api/types";

type Data = {
  loaded: boolean;
  redirecting: boolean;
  page: number;
  maxNumberOfCombosPerPage: number;
  message: string;
  errors: string;
  combos: FormattedApiResponse[];
  sort: SortValue;
  order: OrderValue;
  vendor: VendorValue;
};

export default Vue.extend({
  name: "SearchPage",
  components: {
    ComboResults,
    NoCombosFound,
    SearchPagination,
    SearchMessage,
    StyledSelect,
  },
  data(): Data {
    return {
      loaded: false,
      redirecting: false,
      page: 1,
      maxNumberOfCombosPerPage: 78,
      message: "",
      errors: "",
      combos: [],
      vendor: DEFAULT_VENDOR,
      sort: DEFAULT_SORT,
      order: DEFAULT_ORDER,
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Search Results",
    }
  },
  computed: {
    totalResults(): number {
      return this.combos.length;
    },
    totalPages(): number {
      return Math.floor(this.totalResults / this.maxNumberOfCombosPerPage) + 1;
    },
    startingPoint(): number {
      let startingPoint = (this.page - 1) * this.maxNumberOfCombosPerPage;

      if (startingPoint > this.totalResults) {
        startingPoint = (this.totalPages - 1) * this.maxNumberOfCombosPerPage;
      }

      return startingPoint;
    },
    paginatedResults(): FormattedApiResponse[] {
      let results = this.combos;

      if (this.totalResults > this.maxNumberOfCombosPerPage) {
        results = results.slice(
          this.startingPoint,
          this.startingPoint + this.maxNumberOfCombosPerPage
        );
      }

      return results;
    },
    firstResult(): number {
      return (
        this.page * this.maxNumberOfCombosPerPage -
        this.maxNumberOfCombosPerPage +
        1
      );
    },
    lastResult(): number {
      const finalResult = this.firstResult + this.maxNumberOfCombosPerPage - 1;

      if (finalResult > this.totalResults) {
        return this.totalResults;
      }

      return finalResult;
    },
    sortOptions(): Option[] {
      return [
        { value: "popularity", label: "Popularity" },
        { value: "colors", label: "Color Identity" },
        { value: "price", label: "Price" },
        {
          value: "cards",
          label: "# of Cards",
        },
        {
          value: "prerequisites",
          label: "# of Prerequisites",
        },
        {
          value: "steps",
          label: "# of Steps",
        },
        {
          value: "results",
          label: "# of Results",
        },
        {
          value: "created",
          label: "Date Added to Site",
        },
      ];
    },

    orderOptions(): Option[] {
      return [
        { value: "auto", label: "Auto" },
        { value: "ascending", label: "Asc" },
        { value: "descending", label: "Desc" },
      ];
    },
  },
  watch: {
    "$route.query.q"(): void {
      this.onQueryChange();
    },
    "$route.query.page"(): void {
      this.updatePageFromQuery();
    },
    sort(): void {
      const query = String(this.$route.query.q)
        .replace(/((\s)?sort(:|=)\w*|$)/, ` sort:${this.sort}`)
        .trim();

      this.$router.push({
        path: this.$route.path,
        query: { q: query, page: "1" },
      });
    },
    order(): void {
      let query = String(this.$route.query.q)
        .replace(/((\s)?order(:|=)\w*|$)/g, "")
        .trim();

      if (this.order !== DEFAULT_ORDER) {
        query = `${query} order:${this.order}`;
      }

      this.$router.push({
        path: this.$route.path,
        query: { q: query },
      });
    },
  },
  async mounted(): Promise<void> {
    await this.onQueryChange();
  },
  methods: {
    async onQueryChange(): Promise<void> {
      this.loaded = false;

      const query = this.parseSearchQuery();
      this.updatePageFromQuery();

      if (!query) {
        this.loaded = true;
        return;
      }

      await this.updateSearchResults(query);

      this.loaded = true;
    },
    updatePageFromQuery(): void {
      this.page = Number(this.$route.query.page) || 1;
    },
    async updateSearchResults(query: string): Promise<void> {
      this.combos = [];
      this.message = "";
      this.errors = "";
      this.page = 1;
      this.$router.push({
        path: this.$route.path,
        query: { q: query },
      });

      const { message, sort, order, vendor, errors, combos } = await search(
        query
      );

      if (combos.length === 1) {
        this.redirecting = true;
        this.$router.replace({
          path: `/combo/${combos[0].commanderSpellbookId}/`,
          query: { q: query },
        });
        return;
      }

      this.message = message;
      this.sort = sort;
      this.vendor = vendor;
      this.order = order;
      this.errors = errors.map((e) => e.message).join(" ");
      this.combos = combos;
    },
    parseSearchQuery(): string {
      const query = this.$route.query.q;

      if (!query || typeof query !== "string") {
        return "";
      }

      return query;
    },
    navigateToPage(pagesToChange: number): void {
      this.page = this.page + pagesToChange;
      this.$router.push({
        path: this.$route.path,
        query: { q: this.$route.query.q, page: String(this.page) },
      });
    },
    goForward(): void {
      this.navigateToPage(1);
    },
    goBack(): void {
      this.navigateToPage(-1);
    },
  },
});
</script>

<style scoped>
/* Styles here */
</style>
