// src/components/advancedSearch/MultiSearchInput/MultiSearchInput.tsx
import pluralize from "pluralize";
import { useState } from "react";
import styles from "./multiSearchInput.module.scss";
import StyledSelect from "../../layout/StyledSelect/StyledSelect";
import AutocompleteInput from "../AutocompleteInput/AutocompleteInput";
import Icon, {SpellbookIcon} from "../../layout/Icon/Icon";

type MultiSearchInputValue = {
  value: string;
  operator: string;
  numeric?: boolean;
  negate?: boolean;
  error?: string;
}[];

type Props = {
  value: MultiSearchInputValue;
  autocompleteOptions?: Array<{ value: string; label: string }>;
  selectOptions?: Array<{ value: string; label: string }>;
  useValueForAutocompleteInput?: boolean;
  label: string;
  labelIcon?: SpellbookIcon;
  pluralLabel?: string;
  defaultPlaceholder?: string;
  operatorOptions: Array<{
    operator: string;
    label: string;
    numeric?: boolean;
    negate?: boolean;
    placeholder?: string;
  }>;
  onChange?: (value: MultiSearchInputValue) => void;
};

const MultiSearchInput = ({
  value,
  autocompleteOptions = [],
  useValueForAutocompleteInput,
  label,
  labelIcon,
  pluralLabel,
  defaultPlaceholder,
  operatorOptions,
  onChange,
  selectOptions,
}: Props) => {
  const [inputs, setInputs] = useState<MultiSearchInputValue>(value);

  const inputLabel = pluralLabel || pluralize(label, value.length);

  const addInput = (index: number) =>
    setInputs([
      ...inputs.slice(0, index + 1),
      { value: "", operator: operatorOptions[0].operator },
      ...inputs.slice(index + 1),
    ]);

  const removeInput = (index: number) => {
    const newInputs = [...inputs.slice(0, index), ...inputs.slice(index + 1)];
    setInputs(newInputs);
    onChange && onChange(newInputs);
  }


  const getInputId = (index: number) =>
    `${label.toLowerCase().replace(/\s/g, "-")}-input-${index}`;

  const getSelectId = (index: number) =>
    `${label.toLowerCase().replace(/\s/g, "-")}-select-${index}`;

  const getPlaceHolder = (input: {
    value: string;
    operator: string;
    numeric?: boolean;
    negate?: boolean;
    error?: string;
  }) => {
    const option = operatorOptions.find((option) =>
      option.operator === input.operator &&
      option.numeric === input.numeric &&
      option.negate === input.negate
    );
    if (option && option.numeric == true && !option.placeholder) return `ex: 2`;
    if (!option || !option.placeholder) return defaultPlaceholder || "";
    return option.placeholder;
  };

  const handleSelectChange = (index: number, value: string) => {
    const newInputs = [...inputs];
    const [operator, numeric, negated] = value.split("|");
    newInputs[index].operator = operator;
    newInputs[index].numeric = numeric === "" ? undefined : numeric === "true";
    newInputs[index].negate = negated === "" ? undefined : negated === "true";
    setInputs(newInputs);
    onChange && onChange(newInputs);
  };
  const handleInputChange = (index: number, value: string) => {
    const newInputs = [...inputs];
    newInputs[index].value = value;
    setInputs(newInputs);
    onChange && onChange(newInputs);
  };

  return (
    <div>
      <label className={styles.inputLabel}>{labelIcon && <Icon name={labelIcon}/>} {inputLabel}</label>
      {inputs.map((input, index) => (
        <div
          key={`${label}-input-${index}`}
          className={`my-2 input-wrapper-${index}`}
        >
          <div className="sm:flex">
            <StyledSelect
              label={`Modifier for ${label}`}
              disabled={operatorOptions.length === 1}
              onChange={(value) => handleSelectChange(index, value)}
              id={getSelectId(index)}
              options={operatorOptions.map((option) => ({
                value: option.operator + "|" + (option.numeric ?? "") + "|" + (option.negate ?? ""),
                label: option.label,
              }))}
              selectTextClassName="sm:w-1/2 flex-grow"
              selectBackgroundClassName={`${
                input.error ? "border-danger" : "border-dark"
              } border border-b-0 sm:border-b sm:border-r-0 sm:w-1/2 flex-grow`}
            />
            <div className="w-full flex-grow flex flex-col sm:flex-row">
              {!selectOptions && <AutocompleteInput
                value={input.value}
                onChange={(value) => handleInputChange(index, value)}
                label={inputLabel}
                inputClassName="border-dark"
                autocompleteOptions={autocompleteOptions}
                inputId={getInputId(index)}
                placeholder={getPlaceHolder(input)}
                hasError={!!input.error}
                useValueForInput={useValueForAutocompleteInput}
              />}
              {selectOptions &&
                <StyledSelect
                  label={inputLabel}
                  id={getInputId(index) + '-value'}
                  options={selectOptions}
                  onChange={value => handleInputChange(index, value)}
                  selectBackgroundClassName="flex-grow border-dark border"
                />
              }
              <div className="flex">
                {inputs.length > 1 && (
                  <button
                    type="button"
                    className={`minus-button ${styles.inputButton} ${
                      input.error
                        ? "bg-danger border-danger"
                        : "bg-dark border-dark"
                    } minus-button-${index}`}
                    onClick={() => removeInput(index)}
                  >
                    –
                    <span className="sr-only">
                      Remove {input.value} search query for {label}
                    </span>
                    <span aria-hidden="true" />
                  </button>
                )}
                <button
                  type="button"
                  className={`plus-button ${styles.inputButton} ${
                    input.error
                      ? "bg-danger border-danger"
                      : "bg-dark border-dark"
                  } plus-button-${index}`}
                  onClick={() => addInput(index)}
                >
                  +
                  <span className="sr-only">
                    Remove {input.value} search query for {label}
                  </span>
                  <span aria-hidden="true" />
                </button>
              </div>
            </div>
          </div>
          {input.error && (
            <div
              className={`input-error text-danger w-full py-2 px-4 text-center rounded-b-sm`}
            >
              {input.error}
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

export default MultiSearchInput;

// components/advanced-search/MultiSearchInput.vue
<template>
  <div>
    <label class="input-label">{{ inputLabel }}</label>

    <div
      v-for="(input, index) in inputs"
      :key="`${label}-input-${index}`"
      class="my-2"
      :class="'input-wrapper-' + index"
    >
      <div class="sm:flex">
        <StyledSelect
          :id="label + '-select-' + index"
          v-model="input.operator"
          :label="'Modifier for ' + label"
          :select-background-class="
            input.error
              ? 'border-danger border border-b-0 sm:border-b sm:border-r-0'
              : 'border-dark border border-b-0 sm:border-b sm:border-r-0'
          "
          :options="operatorOptions"
          class="sm:w-1/2 flex-grow"
          :class="{
            ['select-' + index]: true,
          }"
        />

        <div class="w-full flex-grow flex flex-col sm:flex-row">
          <AutocompleteInput
            v-model="input.value"
            :input-id="getInputId(index)"
            :placeholder="getPlaceholder(input.operator)"
            :label="inputLabel"
            input-class="border-dark"
            :autocomplete-options="autocompleteOptions"
            :has-error="Boolean(input.error)"
            :use-value-for-input="useValueForAutocompleteInput"
          />

          <div class="flex">
            <button
              v-if="inputs.length > 1"
              type="button"
              class="minus-button input-button"
              :class="{
                ['minus-button-' + index]: true,
                'bg-dark border-dark': !input.error,
                'bg-danger border-danger': input.error,
              }"
              @click.prevent="removeInput(index)"
            >
              <span class="sr-only"
                >Remove {{ input.value }} search query for {{ label }}</span
              >
              <span aria-hidden="true">−</span>
            </button>
            <button
              type="button"
              class="plus-button input-button sm:rounded-r-sm"
              :class="{
                ['plus-button-' + index]: true,
                'bg-dark border-dark': !input.error,
                'bg-danger border-danger': input.error,
              }"
              @click.prevent="addInput(index)"
            >
              <span class="sr-only"
                >Add an additional search query for {{ label }}</span
              >
              <span aria-hidden="true">+</span>
            </button>
          </div>
        </div>
      </div>
      <div
        v-if="input.error"
        class="input-error text-danger w-full py-2 px-4 text-center rounded-b-sm"
      >
        {{ input.error }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import AutocompleteInput from "@/components/advanced-search/AutocompleteInput.vue";
import StyledSelect from "@/components/StyledSelect.vue";

type MultiSearchInputValue = { value: string; operator: string }[];

export default Vue.extend({
  components: {
    AutocompleteInput,
    StyledSelect,
  },
  props: {
    value: {
      type: Array as PropType<MultiSearchInputValue>,
      default() {
        return [];
      },
    },
    autocompleteOptions: {
      type: Array as PropType<{ value: string; label: string }[]>,
      default() {
        return [];
      },
    },
    useValueForAutocompleteInput: {
      type: Boolean,
      default: false,
    },
    label: {
      type: String,
      default: "",
    },
    pluralLabel: {
      type: String,
      default: "",
    },
    defaultPlaceholder: {
      type: String,
      default: "",
    },
    operatorOptions: {
      type: Array as PropType<
        { value: string; label: string; placeholder?: string }[]
      >,
      default() {
        return [];
      },
    },
    defaultOperator: {
      type: String,
      default: ":",
    },
  },
  computed: {
    inputLabel(): string {
      if (this.inputs.length > 1) {
        if (this.pluralLabel) {
          return this.pluralLabel;
        }

        return `${this.label}s`;
      }

      return this.label;
    },
    inputs: {
      get(): MultiSearchInputValue {
        return this.value;
      },
      set(value: MultiSearchInputValue): void {
        this.$emit("input", value);
      },
    },
  },
  methods: {
    addInput(index: number): void {
      this.inputs.splice(index + 1, 0, {
        value: "",
        operator: this.defaultOperator,
      });
    },
    removeInput(index: number): void {
      this.inputs.splice(index, 1);
    },
    getInputId(index: number): string {
      return `${this.label.toLowerCase().replace(/\s/g, "-")}-input-${index}`;
    },
    getPlaceholder(operator: string): string {
      const isNumber = operator.split("-")[1] === "number";

      if (isNumber) {
        return `ex: ${Math.floor(Math.random() * 4) + 1}`;
      }

      const option = this.operatorOptions.find(
        (option) => option.value === operator
      );

      if (!option || !option.placeholder) {
        return this.defaultPlaceholder || "";
      }

      return option.placeholder;
    },
  },
});
</script>

<style scoped>
.input-label {
  @apply font-semibold;
}

.input-button {
  @apply px-2 text-white flex flex-row items-center text-3xl border flex-grow justify-center;
}
</style>
