// src/components/layout/AnalyticsCookieBanner/AnalyticsCookieBanner.tsx
import { useEffect, useState } from 'react';
import Link from 'next/link';

const AnalyticsCookieBanner = () => {
  const [isOpen, setIsOpen] = useState(false);

  const handleAccept = () => {
    setIsOpen(false);
    localStorage.setItem('GDPR:accepted', 'true');
    location.reload();
  };

  const handleDeny = () => {
    setIsOpen(false);
    localStorage.setItem('GDPR:accepted', 'false');
  };

  useEffect(() => {
    const hasSetGDPRChoice = Boolean(localStorage.getItem('GDPR:accepted') || '');
    setIsOpen(!hasSetGDPRChoice);
  }, []);

  if (!isOpen) {
    return null;
  }

  return (
    <div className="border-b-2 border-dark lg:flex items-center p-4 bg-white shadow-lg justify-center w-full text-dark">
      <div className="text-5xl pb-2 leading-none text-center">🍪</div>
      <div className="lg:mx-8 text-center">
        <p>
          Can we use cookies for analytics? Read&nbsp;
          <Link href="/privacy-policy/">the privacy policy</Link>
          &nbsp;for more information.
        </p>
      </div>
      <div className="flex justify-center mt-4 lg:mt-0">
        <button id="cookie-accept-button" className="button" onClick={handleAccept}>
          Sure!
        </button>
        <button id="cookie-deny-button" className="button" onClick={handleDeny}>
          Nope
        </button>
      </div>
    </div>
  );
};

export default AnalyticsCookieBanner;

// components/AnalyticsCookieBanner.vue
<template>
  <!-- adapted from https://www.carlcassar.com/articles/add-google-analytics-to-a-nuxt-js-app/ -->
  <div
    v-if="isOpen"
    class="border-b-2 border-white lg:flex items-center p-4 bg-dark shadow-lg justify-center w-full text-white"
  >
    <div class="text-5xl pb-2 leading-none text-center">🍪</div>
    <div class="lg:mx-8 text-center">
      <p>
        Can we use cookies for analytics? Read
        <nuxt-link to="/privacy-policy">the privacy policy</nuxt-link>
        for more information.
      </p>
    </div>
    <div class="flex justify-center mt-4 lg:mt-0">
      <button id="cookie-accept-button" class="button" @click="accept">
        Sure!
      </button>
      <button id="cookie-deny-button" class="button" @click="deny">Nope</button>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { bootstrap } from "vue-gtag";

export default Vue.extend({
  data() {
    return {
      isOpen: false,
    };
  },
  mounted(): void {
    // if the user has set it, it will be either the string
    // "true" or "false", so we can show the modal when the
    // value returned from localstorage is undefined
    const hasSetGDPRChoice = Boolean(this.getGDPR());

    this.isOpen = !hasSetGDPRChoice;
  },
  methods: {
    getGDPR(): string {
      if (process.browser) {
        return localStorage.getItem("GDPR:accepted") || "";
      }

      return "";
    },
    accept(): Promise<void> {
      return bootstrap().then(() => {
        this.isOpen = false;
        localStorage.setItem("GDPR:accepted", "true");
        location.reload();
      });
    },
    deny(): void {
      this.isOpen = false;
      localStorage.setItem("GDPR:accepted", "false");
    },
  },
});
</script>

<style scoped>
.button {
  @apply border  px-4 py-2 rounded cursor-pointer mx-2;
}
</style>
