// frontend/components/layout/CardLink/CardLink.tsx
import React from "react"
import ExternalLink from "../ExternalLink/ExternalLink";
import Card from "lib/card";

type Props = {
  name: string
  children?: React.ReactNode
  className?: string
}

const CardLink: React.FC<Props> = ({name, children, className}: Props) => {
  const card = new Card(name)

  let link = ''
  const edhrecLink = card.getEdhrecLink()
  if (edhrecLink) link = edhrecLink
  else {
    let quotes = "%22"
    if (name.includes('"')) quotes = "%27"
    link = `https://scryfall.com/search?q=%21${quotes}${encodeURIComponent(name)}${quotes}`
  }

  return (
    <ExternalLink className={className} href={link}>{children}</ExternalLink>
  )
}

export default CardLink

// components/CardLink.vue
<template>
  <a :href="link" :target="target"><slot /></a>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    name: {
      type: String,
      default: "",
    },
    target: {
      type: String,
      default: "_blank",
    },
  },
  computed: {
    link(): string {
      let quotes = "%22";

      if (this.name.includes('"')) {
        quotes = "%27";
      }

      return `https://scryfall.com/search?q=name%3D${quotes}${encodeURIComponent(
        this.name
      )}${quotes}`;
    },
  },
});
</script>
