// frontend/components/layout/SplashPage/SplashPage.tsx
import ArtCircle, {ArtCircleProps} from "../ArtCircle/ArtCircle"
import styles from './splashPage.module.scss'

type Props = {
  title: string
  flavor: string
  artCircleCardName: ArtCircleProps['cardName']
  pulse?: boolean
  children?: React.ReactNode
}

const SplashPage = ({ title, flavor, artCircleCardName, pulse = false, children }: Props) => {
  return (
    <div className="w-full flex content-center justify-center text-center">
      <div className={`mb-auto mt-auto ${pulse && 'animate-pulse'}`}>
        <h3 className="heading-title">{title}</h3>
        <ArtCircle className="m-auto mt-4 mb-4" cardName={artCircleCardName}/>
        {children}
        <div className={styles.flavorText}><i>{flavor}</i></div>
      </div>
    </div>
  )
}

export default SplashPage

// components/SplashPage.vue
<template>
  <div
    class="w-full sm:pt-32 sm:pb-32 flex content-center justify-center text-center"
  >
    <div :class="{ 'animate-pulse': pulse }" class="mb-auto mt-auto p-10">
      <h3 class="heading-title">{{ title }}</h3>

      <ArtCircle
        class="m-auto mt-4 mb-4"
        :card-name="artCircleCardName"
        :artist="artCircleArtistName"
      />

      <slot />

      <div class="text-xs text-gray-600 w-1/2 m-auto">
        <i class="flavor-text">{{ flavor }}</i>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    title: {
      type: String,
      default: "",
    },
    flavor: {
      type: String,
      default: "",
    },
    artCircleCardName: {
      type: String,
      default: "",
    },
    artCircleArtistName: {
      type: String,
      default: "",
    },
    pulse: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<style>
/* styles here */
</style>
