// frontend/pages/advanced-search.vue
<template>
  <div>
    <div class="container">
      <ArtCircle card-name="Tribute Mage" artist="Scott Murphy" class="m-auto md:block hidden" />
      <h1 class="heading-title">Advanced Search</h1>

      <p class="text-center">
        For more information on the syntax for searches,
        <nuxt-link to="/syntax-guide/">check out the Syntax Guide.</nuxt-link>
      </p>
    </div>

    <form @submit.prevent="submit">
      <div id="card-name-inputs" class="container">
        <MultiSearchInput v-model="cards" label="Card Name" :operator-options="cardOperatorOptions"
          :autocomplete-options="cardNameAutocompletes" />
      </div>

      <div id="card-amount-inputs" class="container">
        <MultiSearchInput v-model="cardAmounts" label="Number of Cards" plural-label="Number of Cards"
          :operator-options="cardAmountOperatorOptions" default-operator="=-number" />
      </div>

      <div id="color-identity-inputs" class="container">
        <MultiSearchInput v-model="colorIdentity" default-placeholder="ex: wug, temur, colorless, black"
          label="Color Identity" plural-label="Color Identities" :operator-options="colorIdentityOperatorOptions"
          :autocomplete-options="colorAutocompletes" :use-value-for-autocomplete-input="true" />
      </div>

      <div id="prerequisite-inputs" class="container">
        <MultiSearchInput v-model="prerequisites" default-placeholder="all permanents on the battlefield"
          label="Prerequisite" :operator-options="comboDataOperatorOptions" />
      </div>

      <div id="step-inputs" class="container">
        <MultiSearchInput v-model="steps" default-placeholder="ex: intruder alarm triggers as well" label="Step"
          :operator-options="comboDataOperatorOptions" />
      </div>

      <div id="result-inputs" class="container">
        <MultiSearchInput v-model="results" default-placeholder="ex: win the game" label="Result"
          :operator-options="comboDataOperatorOptions" :autocomplete-options="resultAutocompletes" />
      </div>

      <div id="price-inputs" class="container">
        <MultiSearchInput v-model="price" label="Price" plural-label="Price" :operator-options="priceOptions"
          default-operator="<-number" />
      </div>

      <div v-if="hasAPriceInQuery" id="vendor" class="container">
        <RadioSearchInput label="Card Vendor" :checked-value="vendor" :options="vendorOptions" form-name="vendor"
          @update-radio="updateRadio('vendor', $event)" />
      </div>

      <div id="popularity-inputs" class="container">
        <MultiSearchInput v-model="popularity" label="Popularity" plural-label="Popularity"
          :operator-options="popularityOptions" default-operator="<-number" />
      </div>

      <div id="previewed-combos" class="container">
        <RadioSearchInput label="Previewed / Spoiled Combos" :checked-value="previewed" :options="previewedOptions"
          form-name="previewed" @update-radio="updateRadio('previewed', $event)" />
      </div>

      <div id="banned-combos" class="container">
        <RadioSearchInput label="Banned Combos" :checked-value="banned" :options="bannedOptions" form-name="banned"
          @update-radio="updateRadio('banned', $event)" />
      </div>

      <div class="container text-center pb-8">
        <div class="flex flex-row items-center">
          <button id="advanced-search-submit-button" type="submit"
            class="border border-link text-link p-4 rounded-l-sm hover:bg-link hover:text-white">
            Search&nbsp;With&nbsp;Query
          </button>
          <div id="search-query"
            class="w-full font-mono border border-gray-200 bg-gray-200 rounded-r-sm text-left p-4 truncate"
            aria-hidden="true">
            <span v-if="query">{{ query }}</span>
            <span v-else class="text-dark">(your query will populate here when you've entered any search
              terms)</span>
          </div>
        </div>

        <div id="advanced-search-validation-error" class="text-danger p-4">
          {{ validationError }}
        </div>
      </div>
    </form>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import colorAutocompletes from "../lib/api/color-autocompletes";
import { DEFAULT_VENDOR } from "../lib/constants";
import ArtCircle from "@/components/ArtCircle.vue";
import MultiSearchInput from "@/components/advanced-search/MultiSearchInput.vue";
import RadioSearchInput from "@/components/advanced-search/RadioSearchInput.vue";

type InputData = {
  value: string;
  operator: string;
  error?: string;
};
type OperatorOption = {
  value: string;
  label: string;
  placeholder?: string;
};

type AutoCompleteOption = {
  value: string;
  label: string;
  alias?: RegExp;
};

type Data = {
  cardNameAutocompletes: AutoCompleteOption[];
  resultAutocompletes: AutoCompleteOption[];
  colorAutocompletes: AutoCompleteOption[];

  cards: InputData[];
  cardOperatorOptions: OperatorOption[];

  cardAmounts: InputData[];
  cardAmountOperatorOptions: OperatorOption[];

  colorIdentity: InputData[];
  colorIdentityOperatorOptions: OperatorOption[];

  prerequisites: InputData[];
  steps: InputData[];
  results: InputData[];
  comboDataOperatorOptions: OperatorOption[];

  price: InputData[];
  priceOptions: OperatorOption[];

  popularity: InputData[];
  popularityOptions: OperatorOption[];

  vendor: string;
  vendorOptions: OperatorOption[];

  validationError: string;

  previewed: string;
  previewedOptions: OperatorOption[];
  banned: string;
  bannedOptions: OperatorOption[];
};

const DEFAULT_PREVIEWED_VALUE = "include";
const DEFAULT_BANNED_VALUE = "exclude";

export default Vue.extend({
  components: {
    ArtCircle,
    MultiSearchInput,
    RadioSearchInput,
  },
  data(): Data {
    return {
      cardNameAutocompletes: require("../../autocomplete-data/cards.json"),
      resultAutocompletes: require("../../autocomplete-data/results.json"),
      colorAutocompletes,

      cards: [{ value: "", operator: ":" }],
      cardOperatorOptions: [
        {
          value: ":",
          label: "Has card with name",
          placeholder: "ex: isochron",
        },
        {
          value: "=",
          label: "Has card with exact name",
          placeholder: "ex: basalt monolith",
        },
        {
          value: ":-exclude",
          label: "Does not have card with name",
          placeholder: "ex: isochron",
        },
        {
          value: "=-exclude",
          label: "Does not have card with exact name",
          placeholder: "ex: basalt monolith",
        },
      ],

      cardAmounts: [{ value: "", operator: "=-number" }],
      cardAmountOperatorOptions: [
        { value: "=-number", label: "Contains exactly x cards (number)" },
        { value: ">-number", label: "Contains more than x cards (number)" },
        { value: "<-number", label: "Contains less than x cards (number)" },
      ],

      colorIdentity: [{ value: "", operator: ":" }],
      colorIdentityOperatorOptions: [
        {
          value: ":",
          label: "Is within the color identity",
        },
        {
          value: "=",
          label: "Is exactly the color identity",
        },
        {
          value: ":-exclude",
          label: "Is not within the color identity",
        },
        {
          value: "=-exclude",
          label: "Is not exactly the color identity",
        },
        { value: ">-number", label: "Contains more than x colors (number)" },
        { value: "<-number", label: "Contains less than x colors (number)" },
        { value: "=-number", label: "Contains exactly x colors (number)" },
      ],

      prerequisites: [{ value: "", operator: ":" }],
      steps: [{ value: "", operator: ":" }],
      results: [{ value: "", operator: ":" }],
      comboDataOperatorOptions: [
        {
          value: ":",
          label: "Contains the phrase",
          placeholder: "ex: mana, untap, additional",
        },
        { value: "=", label: "Is exactly" },
        {
          value: ":-exclude",
          label: "Does not contain the phrase",
          placeholder: "ex: mana, untap, additional",
        },
        { value: "=-exclude", label: "Is not exactly" },
        { value: ">-number", label: "Contains more than x (number)" },
        { value: "<-number", label: "Contains less than x (number)" },
        { value: "=-number", label: "Contains exactly x (number)" },
      ],

      price: [{ value: "", operator: "<-number" }],
      priceOptions: [
        { value: "<-number", label: "Costs less than" },
        { value: ">-number", label: "Costs more than" },
        { value: "=-number", label: "Costs exactly" },
      ],

      popularity: [{ value: "", operator: "<-number" }],
      popularityOptions: [
        { value: "<-number", label: "In less than x decks (number)" },
        { value: ">-number", label: "In more than x decks (number)" },
        { value: "=-number", label: "In exactly x decks (number)" },
      ],

      vendor: DEFAULT_VENDOR,
      vendorOptions: [
        {
          value: "cardkingdom",
          label: "Card Kingdom",
        },
        {
          value: "tcgplayer",
          label: "TCGplayer",
        },
      ],

      previewed: DEFAULT_PREVIEWED_VALUE,
      previewedOptions: [
        {
          value: "include",
          label:
            "Include combos with newly previewed cards in search results (default search behavior)",
        },
        {
          value: "exclude",
          label: "Exclude combos with newly previewed cards in search results",
        },
        {
          value: "is",
          label: "Only show combos with newly previewed cards",
        },
      ],

      banned: DEFAULT_BANNED_VALUE,
      bannedOptions: [
        {
          value: "exclude",
          label:
            "Exclude combos with banned cards in search results (default search behavior)",
        },
        {
          value: "include",
          label: "Include combos with banned cards in search results",
        },
        {
          value: "is",
          label: "Only show combos with banned cards",
        },
      ],

      validationError: "",
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Advanced Search",
    }
  },
  computed: {
    query(): string {
      let query = "";

      this.validate();

      function makeQueryFunction(
        key: string
      ): Parameters<typeof Array.prototype.forEach>[0] {
        return (input: InputData) => {
          const value = input.value.trim();
          const isSimpleValue = value.match(/^[\w\d]*$/);
          const modifier = input.operator.split("-")[1];
          const isNumericOperator = modifier === "number";
          const isExclusionOperator = modifier === "exclude";
          let operator = input.operator.split("-")[0];
          let keyInQuery = key;
          const isSimpleCardValue =
            isSimpleValue &&
            keyInQuery === "card" &&
            operator === ":" &&
            !isExclusionOperator;

          if (!value) {
            return;
          }

          let quotes = "";

          if (!isSimpleValue) {
            quotes = '"';

            if (value.includes(quotes)) {
              quotes = "'";
            }
          }

          if (isSimpleCardValue) {
            keyInQuery = "";
            operator = "";
          } else if (isNumericOperator) {
            if (keyInQuery === "ci") {
              keyInQuery = "colors";
            } else if (keyInQuery === "pre") {
              keyInQuery = "prerequisites";
            } else if (keyInQuery === "popularity") {
              keyInQuery = "decks";
            } else if (keyInQuery !== "price") {
              keyInQuery += "s";
            }
          } else if (isExclusionOperator) {
            keyInQuery = `-${keyInQuery}`;
          }

          query += ` ${keyInQuery}${operator}${quotes}${value}${quotes}`;
        };
      }

      this.cards.forEach(makeQueryFunction("card"));
      this.cardAmounts.forEach(makeQueryFunction("card"));
      this.colorIdentity.forEach(makeQueryFunction("ci"));
      this.prerequisites.forEach(makeQueryFunction("pre"));
      this.steps.forEach(makeQueryFunction("step"));
      this.results.forEach(makeQueryFunction("result"));
      this.price.forEach(makeQueryFunction("price"));
      this.popularity.forEach(makeQueryFunction("popularity"));

      if (this.previewed !== DEFAULT_PREVIEWED_VALUE) {
        query += ` ${this.previewed}:previewed`;
      }
      if (this.banned !== DEFAULT_BANNED_VALUE) {
        query += ` ${this.banned}:banned`;
      }
      if (this.vendor !== DEFAULT_VENDOR && this.hasAPriceInQuery) {
        query += ` vendor:${this.vendor}`;
      }

      query = query.trim();

      return query;
    },
    hasAPriceInQuery(): boolean {
      return Boolean(this.price.find((option) => option.value.trim()));
    },
  },
  methods: {
    submit(): void {
      this.validationError = "";

      if (!this.query) {
        this.validationError = "No search queries entered.";
        return;
      }

      if (this.validate()) {
        this.validationError =
          "Check for errors in your search terms before submitting.";
        return;
      }

      this.$router.push({
        path: "/search/",
        query: {
          q: `${this.query}`,
        },
      });
    },
    validate(): boolean {
      let hasValidationError = false;

      this.validationError = "";

      function val(input: InputData) {
        input.error = "";

        if (input.value.includes("'") && input.value.includes('"')) {
          input.error =
            "Contains both single and double quotes. A card name may only use one kind.";
        }

        if (
          input.operator.split("-")[1] === "number" &&
          !Number.isInteger(Number(input.value))
        ) {
          input.error = "Contains a non-integer. Use a full number instead.";
        }

        if (input.error) {
          hasValidationError = true;
        }
      }

      this.cards.forEach(val);
      this.cardAmounts.forEach(val);
      this.colorIdentity.forEach(val);
      this.prerequisites.forEach(val);
      this.steps.forEach(val);
      this.results.forEach(val);
      this.price.forEach(val);
      this.popularity.forEach(val);

      return hasValidationError;
    },
    updateRadio(model: "banned" | "previewed" | "vendor", value: string): void {
      this[model] = value;
    },
  },
});
</script>

<style scoped>
.container {
  @apply pt-6 mb-6;
}

.subtitle {
  @apply font-light text-3xl;
}
</style>

// src/pages/advanced-search.tsx
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import ArtCircle from "../components/layout/ArtCircle/ArtCircle";
import Link from "next/link";
import MultiSearchInput from "../components/advancedSearch/MultiSearchInput/MultiSearchInput";
import { DEFAULT_VENDOR } from "../lib/constants";
import { useEffect, useState } from "react";
import COLOR_AUTOCOMPLETES from "../lib/colorAutocompletes";
import styles from "./advanced-search.module.scss";
import RadioSearchInput from "../components/advancedSearch/RadioSearchInput/RadioSearchInput";
import { useRouter } from "next/router";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";
import resultAutocompleteData from "assets/autocomplete-data/results.json";
import {SpellbookIcon} from "../components/layout/Icon/Icon";
import CardService from "../services/card.service";

type OperatorOption = {
  operator: string;
  label: string;
  numeric?: boolean;
  negate?: boolean;
  placeholder?: string;
};

type TagOption = {
  name: string;
  label: string;
  labelIcon?: SpellbookIcon;
}

const CARD_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Has card with name",
    placeholder: "ex: isochron",
  },
  {
    operator: "=",
    label: "Has card with exact name",
    placeholder: "ex: basalt monolith",
  },
  {
    operator: ":",
    negate: true,
    label: "Does not have card with name",
    placeholder: "ex: isochron",
  },
  {
    operator: "=",
    negate: true,
    label: "Does not have card with exact name",
    placeholder: "ex: basalt monolith",
  },
];

const CARD_AMOUNT_OPERATOR_OPTIONS: OperatorOption[] = [
  { operator: "=", label: "Contains exactly x cards (number)", numeric: true },
  { operator: ">=", label: "Contains at least x cards (number)", numeric: true },
  { operator: "<", label: "Contains less than x cards (number)", numeric: true },
];

const CARD_TYPE_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Contains the phrase",
    placeholder: "ex: sorcery, instant, artifact",
  },
  {
    operator: "=",
    label: "Is exactly",
    placeholder: "ex: sorcery, instant, artifact",
  },
  {
    operator: ":",
    negate: true,
    label: "Does not contain the phrase",
    placeholder: "ex: sorcery, instant, artifact",
  },
  {
    operator: "=",
    negate: true,
    label: "Is not exactly",
    placeholder: "ex: sorcery, instant, artifact",
  },
];

const CARD_ORACLE_TEXT_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Contains the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  { operator: "=", label: "Is exactly" },
  {
    operator: ":",
    negate: true,
    label: "Does not contain the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  { operator: "=", label: "Is not exactly", negate: true },
];

const CARD_KEYWORD_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Has the keyword",
    placeholder: "ex: cycling, delve, partner",
  },
  {
    operator: ":",
    negate: true,
    label: "Does not have the keyword",
    placeholder: "ex: cycling, delve, partner",
  }
];

const CARD_MANA_VALUE_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: "=",
    label: "Has a mana value of x (number)",
    numeric: true,
  },
  {
    operator: ">=",
    label: "Has a mana value of at least x (number)",
    numeric: true,
  },
  {
    operator: "<",
    label: "Has a mana value of less than x (number)",
    numeric: true,
  },
];

const COLOR_IDENTITY_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Is within the color identity",
  },
  {
    operator: "=",
    label: "Is exactly the color identity",
  },
  {
    operator: ":",
    negate: true,
    label: "Is not within the color identity",
  },
  {
    operator: "=",
    negate: true,
    label: "Is not exactly the color identity",
  },
  { operator: ">=", label: "Contains at least x colors (number)", numeric: true },
  { operator: "<", label: "Contains less than x colors (number)", numeric: true },
  { operator: "=", label: "Contains exactly x colors (number)", numeric: true },
];

const COMBO_DATA_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Contains the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  { operator: "=", label: "Is exactly" },
  { operator: ">=", label: "Contains at least x (number)", numeric: true },
  { operator: "<", label: "Contains less than x (number)", numeric: true },
  {
    operator: ":",
    negate: true,
    label: "Does not contain the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  { operator: "=", label: "Is not exactly", negate: true },
];

const RESULTS_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Contains the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  {
    operator: "=",
    label: "Is exactly",
    placeholder: "ex: Infinite Colorless Mana",
  },
  {
    operator: ":",
    negate: true,
    label: "Does not contain the phrase",
    placeholder: "ex: mana, untap, additional",
  },
  {
    operator: "=",
    negate: true,
    label: "Is not exactly",
    placeholder: "ex: Infinite Colorless Mana",
  },
  { operator: ">=", label: "Contains at least x (number)" , numeric: true },
  { operator: "<", label: "Contains less than x (number)" , numeric: true },
  { operator: "=", label: "Contains exactly x (number)" , numeric: true },
];

const TAGS_OPTIONS: TagOption[] = [
  {
    name: "spoiler",
    label: "Contains a spoiler/previewed card",
    labelIcon: "certificate"
  },
  {
    name: "commander",
    label: "Does the combo require a commander?",
    labelIcon: "commandZone"
  },
]

const COMMANDER_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Requires a commander whose name contains the phrase",
    placeholder: "ex: Krark",
  },
  {
    operator: "=",
    label: "Requires a commander whose name is exactly",
    placeholder: "ex: Krark, the Thumbless",
  },
  {
    operator: ":",
    negate: true,
    label: "Does not require a commander whose name contains the phrase",
    placeholder: "ex: Krark",
  },
  {
    operator: "=",
    negate: true,
    label: "Does not require a commander whose name is exactly",
    placeholder: "ex: Krark, the Thumbless",
  },
];

const POPULARITY_OPTIONS: OperatorOption[] = [
  { operator: ">=", label: "In at least x decks (number)", numeric: true },
  { operator: "<", label: "In less than x decks (number)", numeric: true },
  { operator: "=", label: "In exactly x decks (number)", numeric: true },
];

const PRICE_OPTIONS: OperatorOption[] = [
  {
    operator: "<=",
    label: "Costs at most x",
    placeholder: "ex: 5",
    numeric: true,
  },
  {
    operator: ">=",
    label: "Costs at least x",
    placeholder: "ex: 5",
    numeric: true,
  },
  {
    operator: "=",
    label: "Costs exactly x",
    placeholder: "ex: 5",
  }
];


const PRICE_VENDORS = [
  {
    value: "cardkingdom",
    label: "Card Kingdom",
  },
  {
    value: "tcgplayer",
    label: "TCGPlayer",
  },
  {
    value: "cardmarket",
    label: "Cardmarket",
  },
];

type LegalityFormat = {
  value: string;
  label: string;
}

const LEGALITY_FORMATS: LegalityFormat[] = [
  {
    value: "",
    label: "-",
  },
  {
    value: "commander",
    label: "EDH/Commander",
  },
  {
    value: "pauper_commander",
    label: "Pauper EDH/Commander (including uncommon commanders)",
  },
  {
    value: "pauper_commander_main",
    label: "Pauper EDH/Commander (excluding uncommon commanders)",
  },
  {
    value: "oathbreaker",
    label: "Oathbreaker",
  },
  {
    value: "predh",
    label: "Pre-EDH/Commander",
  },
  {
    value: "brawl",
    label: "Brawl",
  },
  {
    value: "vintage",
    label: "Vintage",
  },
  {
    value: "legacy",
    label: "Legacy",
  },
  {
    value: "modern",
    label: "Modern",
  },
  {
    value: "pioneer",
    label: "Pioneer",
  },
  {
    value: "standard",
    label: "Standard",
  },
  {
    value: "pauper",
    label: "Pauper",
  },
];

const LEGALITY_OPERATOR_OPTIONS: OperatorOption[] = [
  {
    operator: ":",
    label: "Is legal in the format",
  },
  {
    operator: ":",
    label: "Is not legal in the format",
    negate: true,
  },
]

type InputData = {
  value: string;
  operator: string;
  numeric?: boolean;
  negate?: boolean;
  error?: string;
};

interface SelectedTag extends TagOption {
  selected?: boolean;
}

type AutoCompleteOption = {
  value: string;
  label: string;
  alias?: RegExp;
};

type Data = {
  cardNameAutocompletes: AutoCompleteOption[];
  resultAutocompletes: AutoCompleteOption[];
  colorAutocompletes: AutoCompleteOption[];

  cards: InputData[];
  cardAmounts: InputData[];
  cardTypes: InputData[];
  oracleText: InputData[];
  cardKeywords: InputData[];
  manaValue: InputData[];
  colorIdentity: InputData[];
  prerequisites: InputData[];
  steps: InputData[];
  results: InputData[];
  tags: SelectedTag[];
  commanders: InputData[];
  popularity: InputData[];
  prices: InputData[];
  vendor: string;
  format: InputData[];
  validationError: string;
};

const AdvancedSearch = () => {
  const router = useRouter();

  const [formState, setFormStateHook] = useState<Data>({
    cardNameAutocompletes: [],
    resultAutocompletes: resultAutocompleteData,
    colorAutocompletes: COLOR_AUTOCOMPLETES,

    cards: [{ ...CARD_OPERATOR_OPTIONS[0], value: "" }],
    cardAmounts: [{ ...CARD_AMOUNT_OPERATOR_OPTIONS[0], value: "" }],
    cardTypes: [{ ...CARD_TYPE_OPERATOR_OPTIONS[0], value: "" }],
    oracleText: [{ ...CARD_ORACLE_TEXT_OPERATOR_OPTIONS[0], value: "" }],
    cardKeywords: [{ ...CARD_KEYWORD_OPERATOR_OPTIONS[0], value: "" }],
    manaValue: [{ ...CARD_MANA_VALUE_OPERATOR_OPTIONS[0], value: "" }],
    colorIdentity: [{ ...COLOR_IDENTITY_OPERATOR_OPTIONS[0], value: "" }],
    prerequisites: [{ ...COMBO_DATA_OPERATOR_OPTIONS[0], value: "" }],
    steps: [{ ...COMBO_DATA_OPERATOR_OPTIONS[0], value: "" }],
    results: [{ ...RESULTS_OPERATOR_OPTIONS[0], value: "" }],
    tags: TAGS_OPTIONS.map((tag) => ({ ...tag })),
    commanders: [{ ...COMMANDER_OPTIONS[0], value: "" }],
    popularity: [{ ...POPULARITY_OPTIONS[0], value: "" }],
    prices: [{ ...PRICE_OPTIONS[0], value: "" }],
    vendor: DEFAULT_VENDOR,
    format: [{ ...LEGALITY_OPERATOR_OPTIONS[0], value: "" }],
    validationError: "",
  });

  const {
    cardNameAutocompletes,
    resultAutocompletes,
    colorAutocompletes,
    cards,
    cardAmounts,
    cardTypes,
    oracleText,
    cardKeywords,
    manaValue,
    colorIdentity,
    prerequisites,
    steps,
    results,
    tags,
    commanders,
    popularity,
    prices,
    vendor,
    format,
    validationError,
  } = formState;

  const setFormState = (changes: Partial<typeof formState>) => {
    setFormStateHook({ ...formState, ...changes });
  };

  const hasPriceInQuery = !!prices.find(({ value }) => !!value.trim());

  const validate = () => {
    let hasValidationError = false;

    const newFormState = { ...formState };

    function val(input: InputData) {
      input.error = "";

      if (
        (input.numeric ?? false) &&
        !Number.isInteger(Number(input.value))
      ) {
        input.error = "Contains a non-integer. Use a full number instead.";
      }

      if (input.error) {
        hasValidationError = true;
      }
    }

    newFormState.cards.forEach(val);
    newFormState.cardAmounts.forEach(val);
    newFormState.cardTypes.forEach(val);
    newFormState.oracleText.forEach(val);
    newFormState.cardKeywords.forEach(val);
    newFormState.manaValue.forEach(val);
    newFormState.colorIdentity.forEach(val);
    newFormState.prerequisites.forEach(val);
    newFormState.steps.forEach(val);
    newFormState.results.forEach(val);
    newFormState.commanders.forEach(val);
    newFormState.popularity.forEach(val);
    newFormState.prices.forEach(val);
    setFormState(newFormState);
    return hasValidationError;
  };

  useEffect(() => {
    validate();
  }, [
    cards,
    cardAmounts,
    cardTypes,
    oracleText,
    cardKeywords,
    manaValue,
    colorIdentity,
    prerequisites,
    steps,
    results,
    tags,
    commanders,
    popularity,
    prices,
    vendor,
    format,
  ]);

  const getQuery = () => {
    let query = "";

    function makeQueryFunction(
      key: string
    ): Parameters<typeof Array.prototype.forEach>[0] {
      return (input: InputData) => {
        let value = input.value.trim();
        const negated = input.negate ?? false;
        const numeric = input.numeric ?? false;
        const isSimpleValue = value.match(/^[\w\d]*$/);
        let operator = input.operator;
        let keyInQuery = key;
        const isSimpleCardValue =
          isSimpleValue &&
          keyInQuery === "card" &&
          operator === ":" &&
          !negated;

        if (!value) {
          return;
        }

        let quotes = "";

        if (!isSimpleValue) {
          quotes = '"';

          if (value.includes(quotes)) {
            // quotes = "'";
            value = value.replace(/"/g, "\\\"");
          }
        }

        if (isSimpleCardValue) {
          keyInQuery = "";
          operator = "";
        } else if (numeric) {
          if (keyInQuery === "ci") {
            keyInQuery = "colors";
          } else if (keyInQuery === "popularity") {
            keyInQuery = "decks";
          } else if (keyInQuery === "price") {
            keyInQuery = vendor;
          } else if (keyInQuery !== "mv" && keyInQuery !== "pre") {
            keyInQuery += "s";
          }
        }
        if (negated) {
          keyInQuery = `-${keyInQuery}`;
        }

        query += ` ${keyInQuery}${operator}${quotes}${value}${quotes}`;
      };
    }

    function makeQueryFunctionForTags(): Parameters<typeof Array.prototype.forEach>[0] {
      return (tag: SelectedTag) => {
        if (tag.selected === true) {
          query += ` is:${tag.name}`;
        } else if (tag.selected === false) {
          query += ` -is:${tag.name}`;
        }
      };
    }
    cards.forEach(makeQueryFunction("card"));
    cardAmounts.forEach(makeQueryFunction("card"));
    cardTypes.forEach(makeQueryFunction("type"));
    oracleText.forEach(makeQueryFunction("oracle"));
    cardKeywords.forEach(makeQueryFunction("keyword"));
    manaValue.forEach(makeQueryFunction("mv"));
    colorIdentity.forEach(makeQueryFunction("ci"));
    prerequisites.forEach(makeQueryFunction("pre"));
    steps.forEach(makeQueryFunction("step"));
    results.forEach(makeQueryFunction("result"));
    tags.forEach(makeQueryFunctionForTags());
    commanders.forEach(makeQueryFunction("commander"));
    popularity.forEach(makeQueryFunction("popularity"));
    prices.forEach(makeQueryFunction("price"));
    format.forEach(makeQueryFunction("legal"));

    query = query.trim();

    return query;
  };

  const query = getQuery();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!query)
      return setFormState({ validationError: "No search queries entered." });

    if (validate())
      return setFormState({
        validationError:
          "Check for errors in your search terms before submitting.",
      });

    router.push({
      pathname: "/search/",
      query: {
        q: `${query}`,
      },
    });
  };

  useEffect(() => {
    CardService.getNameAutocomplete().then((cardNameAutocompletes) => {
      setFormState({ cardNameAutocompletes });
    });
  }, []);

  return (
    <>
      <SpellbookHead
        title="Commander Spellbook: Advanced Search"
        description="Advanced search form for searching through Commander Spellbook EDH combos."
      />
      <div className={`${styles.container} container`}>
        <ArtCircle cardName="Tribute Mage" className="m-auto md:block hidden" />
        <h1 className="heading-title">Advanced Search</h1>
        <p className="text-center">
          For more information on the syntax for searches,&nbsp;
          <Link href="/syntax-guide/">check out the Syntax Guide.</Link>
        </p>
      </div>

      <form onSubmit={handleSubmit}>
        <div id="card-name-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={cards}
            onChange={(cards) => setFormState({ cards })}
            autocompleteOptions={cardNameAutocompletes}
            label="Card Names"
            labelIcon="signature"
            operatorOptions={CARD_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="card-amount-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={cardAmounts}
            onChange={(cardAmounts) => setFormState({ cardAmounts })}
            label="Number of Cards"
            labelIcon="hashtag"
            pluralLabel="Number of Cards"
            operatorOptions={CARD_AMOUNT_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="card-type-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={cardTypes}
            onChange={(cardTypes) => setFormState({ cardTypes })}
            label="Card Type Line"
            labelIcon="seedling"
            pluralLabel="Card Type Lines"
            operatorOptions={CARD_TYPE_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="card-oracle-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={oracleText}
            onChange={(oracleText) => setFormState({ oracleText })}
            label="Oracle Text"
            labelIcon="fileLines"
            pluralLabel="Oracle Text"
            operatorOptions={CARD_ORACLE_TEXT_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="card-keywords-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={cardKeywords}
            onChange={(cardKeywords) => setFormState({ cardKeywords })}
            label="Card Keyword"
            labelIcon="key"
            pluralLabel="Card Keywords"
            operatorOptions={CARD_KEYWORD_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="card-mana-value-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={manaValue}
            onChange={(manaValue) => setFormState({ manaValue })}
            label="Mana Value"
            labelIcon="coins"
            pluralLabel="Card Mana Values"
            operatorOptions={CARD_MANA_VALUE_OPERATOR_OPTIONS}
          />
        </div>

        <div
          id="color-identity-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={colorIdentity}
            onChange={(colorIdentity) => setFormState({ colorIdentity })}
            label="Color Identity"
            labelIcon="palette"
            pluralLabel="Color Identities"
            operatorOptions={COLOR_IDENTITY_OPERATOR_OPTIONS}
            autocompleteOptions={colorAutocompletes}
            defaultPlaceholder="ex: wug, temur, colorless, black"
            useValueForAutocompleteInput
          />
        </div>

        <div
          id="prerequisite-inputs"
          className={`${styles.container} container`}
        >
          <MultiSearchInput
            value={prerequisites}
            onChange={(prerequisites) => setFormState({ prerequisites })}
            defaultPlaceholder="all permanents on the battlefield"
            label="Prerequisite"
            labelIcon="listCheck"
            operatorOptions={COMBO_DATA_OPERATOR_OPTIONS}
          />
        </div>

        <div id="step-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={steps}
            onChange={(steps) => setFormState({ steps })}
            label="Step"
            labelIcon="listOl"
            operatorOptions={COMBO_DATA_OPERATOR_OPTIONS}
          />
        </div>

        <div id="result-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={results}
            onChange={(results) => setFormState({ results })}
            autocompleteOptions={resultAutocompletes}
            label="Result"
            labelIcon="infinity"
            operatorOptions={COMBO_DATA_OPERATOR_OPTIONS}
            defaultPlaceholder="ex: win the game"
          />
        </div>

        <div id="commander-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={commanders}
            onChange={(commanders) => setFormState({ commanders })}
            autocompleteOptions={cardNameAutocompletes}
            label="Commander"
            labelIcon="commandZone"
            operatorOptions={COMMANDER_OPTIONS}
            defaultPlaceholder="ex: Codie, Vociferous Codex"
          />
        </div>

        <div id="popularity-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={popularity}
            onChange={(popularity) => setFormState({ popularity })}
            label="Popularity"
            labelIcon="arrowUpRightDots"
            pluralLabel="Popularity"
            operatorOptions={POPULARITY_OPTIONS}
          />
        </div>

        <div id="price-inputs" className={`${styles.container} container`}>
          <MultiSearchInput
            value={prices}
            onChange={(prices) => setFormState({ prices })}
            label="Price"
            labelIcon="dollarSign"
            pluralLabel="Price"
            operatorOptions={PRICE_OPTIONS}
          />
        </div>

        {hasPriceInQuery && (
          <div id="vendor" className={`${styles.container} container`}>
            <RadioSearchInput
              checkedValue={vendor}
              options={PRICE_VENDORS}
              formName="vendor"
              label="Card Vendor"
              labelIcon="cartShopping"
              onChange={(vendor) => setFormState({ vendor })}
            />
          </div>
        )}

        <div id="format" className={`${styles.container} container`}>
          <MultiSearchInput
            value={format}
            operatorOptions={LEGALITY_OPERATOR_OPTIONS}
            selectOptions={LEGALITY_FORMATS}
            label="Format"
            labelIcon="scaleBalanced"
            onChange={(format) => setFormState({ format })}
          />
        </div>

        {TAGS_OPTIONS.map((tagOption, i) => (
          <div id={`${tagOption.name}-tag`} className={`${styles.container} container`} key={i}>
            <RadioSearchInput
              checkedValue={tags.find((tag) => tag.name === tagOption.name)?.selected?.toString() ?? "null"}
              options={[{ value: "true", label: "Yes" }, { value: "false", label: "No" }, { value: "null", label: "Either"}]}
              formName={tagOption.name}
              label={tagOption.label}
              labelIcon={tagOption.labelIcon}
              onChange={(tag) => {
                const tagIndex = tags.findIndex((t) => t.name === tagOption.name);
                const newTag = {
                    ...tagOption,
                    selected: tag === "null" ? undefined : tag === "true",
                };
                setFormState({
                  tags: tagIndex === -1 ? tags.concat(newTag) : tags.map((t, i) => i === tagIndex ? newTag : t)
                });
              }}
            />
          </div>
        ))}

        <div className={`${styles.container} container text-center pb-8`}>
          <div className="flex flex-row items-center">
            <button
              id="advanced-search-submit-button"
              type="submit"
              className="border border-link text-link p-4 rounded-l-sm hover:bg-link hover:text-white"
            >
              Search&nbsp;With&nbsp;Query
            </button>

            <div
              id="search-query"
              className="w-full font-mono border border-gray-200 bg-gray-200 rounded-r-sm text-left p-4 truncate"
              aria-hidden="true"
            >
              {query ? (
                <span>{query}</span>
              ) : (
                <span className="text-dark">
                  (your query will populate here when you've entered any search
                  terms)
                </span>
              )}
            </div>
          </div>

          <div
            id="advanced-search-validation-error"
            className="text-danger p-4"
          >
            {validationError}
          </div>
        </div>
      </form>
    </>
  );
};

export default AdvancedSearch;
