// frontend/pages/find-my-combos.vue
<template>
  <div class="static-page">
    <ArtCircle card-name="Exploration" artist="Florian de Gesincourt" class="m-auto md:block hidden" />
    <h1 class="heading-title text-center">Find My Combos</h1>
    <h2 class="heading-subtitle text-center mt-0">
      Uncover combos in your deck, and discover potential combos.
    </h2>

    <label for="decklist-input" class="sr-only">Copy and paste your decklist into the text box to discover the combos in
      your deck.</label>

    <section>
      <textarea id="decklist-input" v-model="decklist" placeholder="Supported decklist formats:
Ancient Tomb
1 Ancient Tomb
1x Ancient Tomb
Ancient Tomb (uma) 236
" @input="onInput">
      </textarea>

      <span v-if="decklist" id="decklist-card-count" class="gradient" aria-hidden="true">{{
        numberOfCardsText
      }}</span>
      <button v-if="decklist" id="clear-decklist-input" class="button" @click="clearDecklist">
        Clear Decklist
      </button>

      <div v-if="!decklist" id="decklist-hint" class="heading-subtitle" aria-hidden="true">
        Paste your decklist
      </div>
    </section>

    <div id="decklist-app">
      <section v-if="lookupInProgress">
        <h2 class="heading-subtitle">Loading Combos...</h2>
      </section>

      <section v-if="!lookupInProgress && decklist" id="combos-in-deck-section">
        <h2 class="heading-subtitle">{{ combosInDeckHeadingText }}</h2>

        <ComboResults :results="combosInDeck" />
      </section>

      <section v-if="!lookupInProgress && potentialCombosMatchingDeckColorIdentity.length > 0"
        id="potential-combos-in-deck-section">
        <h2 class="heading-subtitle">{{ potentialCombosInDeckHeadingText }}</h2>
        <p>
          List of combos where your decklist is missing 1 combo piece.
        </p>

        <ComboResults :results="potentialCombosMatchingDeckColorIdentity"
          :missing-decklist-cards="missingDecklistCards" />
      </section>

      <section v-if="!lookupInProgress && potentialCombosOutsideDeckColorIdentity.length > 0"
        id="potential-combos-outside-color-identity-section">
        <h2 class="heading-subtitle">{{ potentialCombosInAdditionalColorsHeadingText }}</h2>
        <p>
          List of combos where your decklist is missing 1 combo piece, but requires at least one additional color.
          Toggle the
          color symbols to filter for identity.
        </p>

        <ColorIdentityPicker v-model="potentialCombosColorIdentity" class="mb-4"
          :chosen-colors="potentialCombosColorIdentity" />

        <ComboResults :results="potentialCombosOutsideDeckColorIdentityFilteredByPicker"
          :missing-decklist-cards="missingDecklistCards" />
        <h2 v-if="potentialCombosOutsideDeckColorIdentityFilteredByPicker.length === 0" class="heading-subtitle">No
          Combos Found Matching the Selected Color Identity</h2>
      </section>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
// eslint-disable-next-line import/no-named-as-default
import debounce from "debounce";
import ArtCircle from "@/components/ArtCircle.vue";
import ComboResults from "@/components/search/ComboResults.vue";
import ColorIdentityPicker from "@/components/ColorIdentityPicker.vue";
import {
  findCombosFromDecklist,
  convertDecklistToDeck,
} from "@/lib/decklist-parser";

import type { FormattedApiResponse, ColorIdentityColors } from "@/lib/api/types";
import type Card from "@/lib/api/models/card";

type ComboFinderData = {
  decklist: string;
  numberOfCardsInDeck: number;
  lookupInProgress: boolean;
  combosInDeck: FormattedApiResponse[];
  potentialCombos: FormattedApiResponse[];
  missingDecklistCards: Card[];
  potentialCombosColorIdentity: ColorIdentityColors[];
  deckColorIdentity: ColorIdentityColors[];
};

const LOCAL_STORAGE_DECK_STORAGE_KEY =
  "commander-spellbook-combo-finder-last-decklist";

export default Vue.extend({
  components: {
    ArtCircle,
    ComboResults,
    ColorIdentityPicker,
  },
  data(): ComboFinderData {
    return {
      decklist: "",
      numberOfCardsInDeck: 0,
      lookupInProgress: false,
      combosInDeck: [],
      potentialCombos: [],
      missingDecklistCards: [],
      potentialCombosColorIdentity: ["w", "u", "b", "r", "g"],
      deckColorIdentity: [],
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Find My Combos",
    }
  },
  computed: {
    numberOfCardsText(): string {
      return `${this.numberOfCardsInDeck} ${this.$pluralize(
        "card",
        this.numberOfCardsInDeck
      )}`;
    },
    combosInDeckHeadingText(): string {
      const numOfCombos = this.combosInDeck.length;

      if (numOfCombos === 0) {
        return "No Combos Found";
      }

      return `${numOfCombos} ${this.$pluralize("Combo", numOfCombos)} Found`;
    },
    potentialCombosInDeckHeadingText(): string {
      const numOfCombos = this.potentialCombosMatchingDeckColorIdentity.length;

      return `${numOfCombos} Potential ${this.$pluralize(
        "Combo",
        numOfCombos
      )} Found`;
    },
    potentialCombosInAdditionalColorsHeadingText(): string {
      const numOfCombos = this.potentialCombosOutsideDeckColorIdentity.length;

      return `${numOfCombos} Potential ${this.$pluralize(
        "Combo",
        numOfCombos
      )} Found With Additional Color Requirements`;
    },
    potentialCombosMatchingDeckColorIdentity(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return combo.colorIdentity.isWithin(this.deckColorIdentity);
      });
    },
    potentialCombosOutsideDeckColorIdentity(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return !combo.colorIdentity.isWithin(this.deckColorIdentity);
      });
    },
    potentialCombosOutsideDeckColorIdentityFilteredByPicker(): FormattedApiResponse[] {
      return this.potentialCombosOutsideDeckColorIdentity.filter((combo) => {
        return combo.colorIdentity.isWithin(this.potentialCombosColorIdentity);
      })
    },
    potentialCombosMatchingColorIdentityPicker(): FormattedApiResponse[] {
      return this.potentialCombos.filter((combo) => {
        return combo.colorIdentity.isWithin(this.potentialCombosColorIdentity);
      });
    }
  },
  mounted() {
    const savedDeck = localStorage.getItem(LOCAL_STORAGE_DECK_STORAGE_KEY);

    if (savedDeck?.trim()) {
      this.decklist = savedDeck;
      this.lookupCombos();
    }
  },
  methods: {
    onInput: debounce(function () {
      // @ts-ignore
      this.lookupCombos();
    }, 1000),
    async lookupCombos() {
      this.lookupInProgress = true;

      const deck = await convertDecklistToDeck(this.decklist);
      this.numberOfCardsInDeck = deck.numberOfCards;

      this.combosInDeck = [];
      this.potentialCombos = [];
      this.missingDecklistCards = [];
      this.potentialCombosColorIdentity = ["w", "u", "b", "r", "g"];
      this.deckColorIdentity = deck.colorIdentity;

      // not possible to have any combos if deck has 1
      // or fewer card in it, so we can skip the lookup
      if (this.numberOfCardsInDeck < 2) {
        this.lookupInProgress = false;
        return;
      }

      localStorage.setItem(LOCAL_STORAGE_DECK_STORAGE_KEY, this.decklist);

      // TODO: let's debounce in case some weirdo is manually
      // typing in their deck list
      const combos = await findCombosFromDecklist(deck.cards);

      this.combosInDeck = combos.combosInDecklist;
      this.potentialCombos = combos.potentialCombos;
      this.missingDecklistCards = combos.missingCardsForPotentialCombos;

      this.lookupInProgress = false;
    },

    clearDecklist() {
      this.decklist = "";
      this.combosInDeck = [];
      this.potentialCombos = [];
      localStorage.removeItem(LOCAL_STORAGE_DECK_STORAGE_KEY);
    },
  },
});
</script>

<style scoped>
p {
  @apply my-4;
}

section {
  @apply flex flex-col items-center justify-center py-4;
}

#decklist-input {
  @apply h-80 w-full py-2 px-4 pb-6 mt-4 border-2 border-dark resize-none;
}

#decklist-input:active {
  @apply border-primary;
}

#decklist-input:focus {
  @apply border-primary;
}

#clear-decklist-input {
  @apply cursor-pointer;
}

#decklist-card-count {
  @apply border-2 border-dark w-1/3 text-center py-2 -mt-4;
}

#decklist-app {
  @apply py-4;
}

#decklist-hint {
  @apply flex relative text-center items-center justify-center flex-col -my-10 mb-8;
}

#decklist-hint::before {
  content: "";
  height: 90px;
  width: 20px;
  background-image: url("~assets/svgs/combo-finder-arrow-hint.svg");

  @apply block bg-center bg-no-repeat bg-contain;
}

@media (min-width: 768px) {
  #decklist-input {
    @apply w-2/3;
  }
}
</style>

// src/pages/find-my-combos.tsx
import { useEffect, useState } from "react";
import pluralize from "pluralize";
import {Variant} from "../lib/types";
import {convertDecklistToDeck, Deck} from "../lib/decklist-parser";
import styles from "./find-my-combos.module.scss";
import ArtCircle from "../components/layout/ArtCircle/ArtCircle";
import ComboResults from "../components/search/ComboResults/ComboResults";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";
import findMyCombosService from "../services/findMyCombos.service";
import { isValidHttpUrl } from "../lib/url-check";
import decklistService from "../services/decklist.service";
import { ErrorResult } from "../services/decklist.service";
import ErrorMessage from "components/submission/ErrorMessage/ErrorMessage";

const LOCAL_STORAGE_DECK_STORAGE_KEY =
  "commander-spellbook-combo-finder-last-decklist";
const LOCAL_STORAGE_COMMANDER_STORAGE_KEY =
  "commander-spellbook-combo-finder-last-commander";


const DEFAULT_RESULTS = {
  identity: "",
  included: [],
  includedByChangingCommanders: [],
  almostIncluded: [],
  almostIncludedByChangingCommanders: [],
  almostIncludedByAddingColors: [],
  almostIncludedByAddingColorsAndChangingCommanders: [],
}

const FindMyCombos = () => {
  const [decklist, setDecklist] = useState<string>("");
  const [deckUrlHint, setDeckUrlHint] = useState<string>("");
  const [deckUrl, setDeckUrl] = useState<string>("");
  const [commanderList, setCommanderList] = useState<string>("");
  const [numberOfCardsInDeck, setNumberOfCardsInDeck] = useState<number>(0);
  const [lookupInProgress, setLookupInProgress] = useState<boolean>(false);
  const [currentlyParsedDeck, setCurrentlyParsedDeck] = useState<Deck>();
  const [results, setResults] = useState<{
    identity: string,
    included: Variant[],
    includedByChangingCommanders: Variant[],
    almostIncluded: Variant[],
    almostIncludedByChangingCommanders: Variant[],
    almostIncludedByAddingColors: Variant[],
    almostIncludedByAddingColorsAndChangingCommanders: Variant[],
  }>(DEFAULT_RESULTS)

  const numberOfCardsText = `${numberOfCardsInDeck} ${pluralize(
    "card",
    numberOfCardsInDeck
  )}`;

  const numOfCombos = results.included.length;
  const combosInDeckHeadingText = !numOfCombos
    ? "No combos found"
    : `${numOfCombos} ${pluralize("Combo", numOfCombos)} Found`;

  const numPotentialCombos = results.almostIncluded.length;
  const potentialCombosInDeckHeadingText = `${numPotentialCombos} Potential ${pluralize(
    "Combo",
    numPotentialCombos
  )} Found`;

  const potentialCombosInAdditionalColorsHeadingText = `${results.almostIncludedByAddingColors.length} Potential ${pluralize(
    "Combo",
    results.almostIncludedByAddingColors.length
  )} Found With Additional Color Requirements`;

  const lookupCombos = async (newDeckList: string, newCommanderList: string, forwardedResults?: typeof results, next?: string, page=1): Promise<any> => {
    setLookupInProgress(true);
    const deck = await convertDecklistToDeck(newDeckList + "\n" + newCommanderList);
    setNumberOfCardsInDeck(deck.numberOfCards);

    if (deck.numberOfCards < 2) return setLookupInProgress(false);

    localStorage.setItem(LOCAL_STORAGE_DECK_STORAGE_KEY, newDeckList);
    localStorage.setItem(LOCAL_STORAGE_COMMANDER_STORAGE_KEY, newCommanderList);

    const combos = await findMyCombosService.findFromString(newDeckList, newCommanderList, next)

    setCurrentlyParsedDeck(deck)
    const newResults = {
      identity: combos.results.identity,
      included: (forwardedResults?.included || []).concat(combos.results.included),
      includedByChangingCommanders: (forwardedResults?.includedByChangingCommanders || []).concat(combos.results.includedByChangingCommanders),
      almostIncluded: (forwardedResults?.almostIncluded || []).concat(combos.results.almostIncluded),
      almostIncludedByChangingCommanders: (forwardedResults?.almostIncludedByChangingCommanders || []).concat(combos.results.almostIncludedByChangingCommanders),
      almostIncludedByAddingColors: (forwardedResults?.almostIncludedByAddingColors || []).concat(combos.results.almostIncludedByAddingColors),
      almostIncludedByAddingColorsAndChangingCommanders: (forwardedResults?.almostIncludedByAddingColorsAndChangingCommanders || []).concat(combos.results.almostIncludedByAddingColorsAndChangingCommanders),
    }

    if (combos.next && page < 5) return lookupCombos(newDeckList, newCommanderList, newResults, combos.next, page+1); // Adding a page limit to prevent infinite loops

    setResults(newResults)
    setLookupInProgress(false);
  };

  const clearDecklist = () => {
    setCurrentlyParsedDeck(undefined)
    setDecklist("");
    setCommanderList("");
    setResults(DEFAULT_RESULTS)
    localStorage.removeItem(LOCAL_STORAGE_DECK_STORAGE_KEY);
    localStorage.removeItem(LOCAL_STORAGE_COMMANDER_STORAGE_KEY);
  };

  useEffect(() => {
    const savedDeck = localStorage.getItem(LOCAL_STORAGE_DECK_STORAGE_KEY);
    const savedCommanderList = localStorage.getItem(LOCAL_STORAGE_COMMANDER_STORAGE_KEY);

    if (!savedDeck?.trim()) return;

    setDecklist(savedDeck);
    setCommanderList(savedCommanderList || "");

    lookupCombos(savedDeck, savedCommanderList || "");
  }, []);

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setDecklist(e.target.value);
  };

  const handleUrlInput = async () => {
    if (!isValidHttpUrl(deckUrl)) {
      setDeckUrl("");
      setDeckUrlHint("You must paste a valid URL.");
      return;
    }
    try {
      const deck = await decklistService.getCardsFromUrl(deckUrl);
      setDeckUrlHint("");
      const decklist = deck.main.join("\n");
      const commanderList = deck.commanders.join("\n");
      setDecklist(decklist);
      setCommanderList(commanderList);
      lookupCombos(decklist, commanderList);
    } catch (error: any) {
      const err = error as ErrorResult;
      setDeckUrlHint(err.error);
    }
  };

  return (
    <>
      <SpellbookHead
        title="Commander Spellbook: Find My Combos"
        description="Input a decklist to generate all possible combos in your deck as well as combo suggestions."
      />
      <div className={`${styles.findMyCombosContainer} static-page`}>
        <ArtCircle cardName="Exploration" className="m-auto md:block hidden" />
        <h1 className="heading-title text-center">Find My Combos</h1>
        <h2 className="heading-subtitle text-center mt-0">
          Uncover combos in your deck, and discover potential combos.
        </h2>
        <label htmlFor="decklist-input" className="sr-only">
          Copy and paste your decklist into the text box to discover the combos
          in your deck.
        </label>
        <section>
          <label>Commanders:</label>
          <textarea
            id="commander-input"
            className={`${styles.decklistInput} ${styles.commanderInput}`}
            value={commanderList}
            placeholder={`ex: Ezuri, Claw of Progress`}
            onChange={(e) => setCommanderList(e.target.value)}
          />
          <textarea
            id="decklist-input"
            className={styles.decklistInput}
            value={decklist}
            placeholder={`Supported decklist formats:
              Ancient Tomb
              1 Ancient Tomb
              1x Ancient Tomb
              Ancient Tomb (uma) 236
              `}
            onChange={handleInput}
          />

          {!!decklist && (
            <>
              <span
                id="decklist-card-count"
                className={`${styles.decklistCardCount} gradient relative`}
                aria-hidden="true"
              >
                {numberOfCardsText}
              </span>
              <button
                id="clear-decklist-input"
                className={`${styles.clearDecklistInput} button`}
                onClick={() => lookupCombos(decklist, commanderList)}
              >
                Find New Combos!
              </button>
              <button
                id="clear-decklist-input"
                className={`${styles.clearDecklistInput} button`}
                onClick={clearDecklist}
              >
                Clear Decklist
              </button>
            </>
          )}

          {!decklist && (
            <div
              id="decklist-hint"
              className={`${styles.decklistHint} heading-subtitle`}
              aria-hidden="true"
            >
              Paste your decklist
            </div>
          )}

          {!decklist && (
            <section>
              <p className={`${styles.or} heading-subtitle`}>
                or
              </p>
              <input
                id="decklist-url-input"
                className={styles.decklistInput}
                type="text"
                value={deckUrl}
                placeholder="Supported deckbuilding sites: Archidekt, Moxfield."
                onChange={(e) => setDeckUrl(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') handleUrlInput() }}
              />
              <div
                id="decklist-url-hint"
                className={`${styles.decklistHint} heading-subtitle`}
                aria-hidden="true"
              >
                Paste your decklist url
              </div>
              <button
                id="submit-url-input"
                className={`${styles.clearDecklistInput} button`}
                onClick={handleUrlInput}
              >
                Submit URL
              </button>
              {deckUrlHint &&
                <ErrorMessage>
                  {deckUrlHint}
                </ErrorMessage>
              }
            </section>
          )}
        </section>

        <div id="decklist-app" className={styles.decklistApp}>
          {lookupInProgress && (
            <section>
              <h2 className="heading-subtitle">Loading Combos...</h2>
            </section>
          )}

          {!lookupInProgress && decklist && (
            <section id="combos-in-deck-section">
              <h2 className="heading-subtitle">{combosInDeckHeadingText}</h2>
              <ComboResults results={results.included} />
            </section>
          )}

          {!lookupInProgress &&
            !!results.almostIncluded.length && (
              <section id="potential-combos-in-deck-section">
                <h2 className="heading-subtitle">
                  {potentialCombosInDeckHeadingText}
                </h2>
                <p>
                  List of combos where your decklist is missing 1 combo piece.
                </p>
                <ComboResults
                  results={results.almostIncluded}
                  deck={currentlyParsedDeck}
                />
              </section>
            )}

          {!lookupInProgress && !!results.almostIncludedByAddingColors.length &&
              <section id="potential-combos-outside-color-identity-section">
                <h2 className="heading-subtitle">
                  {potentialCombosInAdditionalColorsHeadingText}
                </h2>
                <p>
                  List of combos where your decklist is missing 1 combo piece,
                  but requires at least one additional color.
                </p>
                <ComboResults
                  results={results.almostIncludedByAddingColors}
                  deck={currentlyParsedDeck}
                />
              </section>
            }
          {!lookupInProgress && !!results.almostIncludedByChangingCommanders.length &&
            <section id="potential-combos-outside-commander-section">
              <h2 className="heading-subtitle">
                {results.almostIncludedByChangingCommanders.length} Potential Combos Found With Different Commander
              </h2>
              <p>
                List of combos where your decklist is missing 1 combo piece,
                but requires changing your commander.
              </p>
              <ComboResults
                results={results.almostIncludedByChangingCommanders}
                deck={currentlyParsedDeck}
              />
            </section>
          }
          {!lookupInProgress && !!results.almostIncludedByAddingColorsAndChangingCommanders.length &&
            <section id="potential-combos-outside-color-identity-and-commander-section">
              <h2 className="heading-subtitle">
                {results.almostIncludedByAddingColorsAndChangingCommanders.length} Potential Combos Found With Different Commander and Additional Colors
              </h2>
              <p>
                List of combos where your decklist is missing 1 combo piece,
                but requires changing your commander and adding a color.
              </p>
              <ComboResults
                results={results.almostIncludedByAddingColorsAndChangingCommanders}
                deck={currentlyParsedDeck}
              />
            </section>
          }
        </div>
      </div>
    </>
  );
};

export default FindMyCombos;
