// frontend/pages/search.vue
<template>
  <div>
    <h1 class="sr-only">Search Results</h1>

    <SearchMessage :message="message" :errors="errors" :current-page="page" :total-pages="totalPages"
      :max-number-of-combos-per-page="maxNumberOfCombosPerPage" :total-results="totalResults" />

    <div v-if="paginatedResults.length > 0" class="border-b border-light">
      <div class="container sm:flex flex-row items-center justify-center">
        <div class="mr-2 sm:mt-0 mt-2" aria-hidden="true">Sorted by</div>
        <StyledSelect id="sort-combos-select" v-model="sort" class="my-2 sm:mr-2"
          select-background-class="border-dark border-2" select-text-class="text-dark"
          label="Change how combos are sorted" :options="sortOptions" />
        <div class="mx-1 hidden sm:block" aria-hidden="true">:</div>
        <StyledSelect id="order-combos-select" v-model="order" class="sm:m-2"
          select-background-class="border-dark border-2" select-text-class="text-dark"
          label="Change sort direction, ascending or descending" :options="orderOptions" />
        <div class="flex-grow"></div>
        <SearchPagination :current-page="page" :total-pages="totalPages" aria-hidden="true" @go-forward="goForward"
          @go-back="goBack" />
      </div>
    </div>

    <div class="container sm:flex flex-row">
      <div v-if="paginatedResults.length > 0" class="w-full">
        <ComboResults :results="paginatedResults" :sort="sort" :vendor="vendor" />

        <SearchPagination :current-page="page" :total-pages="totalPages" @go-forward="goForward" @go-back="goBack" />
      </div>

      <NoCombosFound v-else :loaded="loaded && !redirecting" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import ComboResults from "@/components/search/ComboResults.vue";
import NoCombosFound from "@/components/search/NoCombosFound.vue";
import SearchPagination from "@/components/search/SearchPagination.vue";
import SearchMessage from "@/components/search/SearchMessage.vue";
import StyledSelect, { Option } from "@/components/StyledSelect.vue";
import search from "@/lib/api/search";
import { DEFAULT_ORDER, DEFAULT_SORT, DEFAULT_VENDOR } from "@/lib/constants";

import type {
  FormattedApiResponse,
  SortValue,
  OrderValue,
  VendorValue,
} from "@/lib/api/types";

type Data = {
  loaded: boolean;
  redirecting: boolean;
  page: number;
  maxNumberOfCombosPerPage: number;
  message: string;
  errors: string;
  combos: FormattedApiResponse[];
  sort: SortValue;
  order: OrderValue;
  vendor: VendorValue;
};

export default Vue.extend({
  name: "SearchPage",
  components: {
    ComboResults,
    NoCombosFound,
    SearchPagination,
    SearchMessage,
    StyledSelect,
  },
  data(): Data {
    return {
      loaded: false,
      redirecting: false,
      page: 1,
      maxNumberOfCombosPerPage: 78,
      message: "",
      errors: "",
      combos: [],
      vendor: DEFAULT_VENDOR,
      sort: DEFAULT_SORT,
      order: DEFAULT_ORDER,
    };
  },
  head() {
    return {
      title: "Commander Spellbook: Search Results",
    }
  },
  computed: {
    totalResults(): number {
      return this.combos.length;
    },
    totalPages(): number {
      return Math.floor(this.totalResults / this.maxNumberOfCombosPerPage) + 1;
    },
    startingPoint(): number {
      let startingPoint = (this.page - 1) * this.maxNumberOfCombosPerPage;

      if (startingPoint > this.totalResults) {
        startingPoint = (this.totalPages - 1) * this.maxNumberOfCombosPerPage;
      }

      return startingPoint;
    },
    paginatedResults(): FormattedApiResponse[] {
      let results = this.combos;

      if (this.totalResults > this.maxNumberOfCombosPerPage) {
        results = results.slice(
          this.startingPoint,
          this.startingPoint + this.maxNumberOfCombosPerPage
        );
      }

      return results;
    },
    firstResult(): number {
      return (
        this.page * this.maxNumberOfCombosPerPage -
        this.maxNumberOfCombosPerPage +
        1
      );
    },
    lastResult(): number {
      const finalResult = this.firstResult + this.maxNumberOfCombosPerPage - 1;

      if (finalResult > this.totalResults) {
        return this.totalResults;
      }

      return finalResult;
    },
    sortOptions(): Option[] {
      return [
        { value: "popularity", label: "Popularity" },
        { value: "colors", label: "Color Identity" },
        { value: "price", label: "Price" },
        {
          value: "cards",
          label: "# of Cards",
        },
        {
          value: "prerequisites",
          label: "# of Prerequisites",
        },
        {
          value: "steps",
          label: "# of Steps",
        },
        {
          value: "results",
          label: "# of Results",
        },
        {
          value: "created",
          label: "Date Added to Site",
        },
      ];
    },

    orderOptions(): Option[] {
      return [
        { value: "auto", label: "Auto" },
        { value: "ascending", label: "Asc" },
        { value: "descending", label: "Desc" },
      ];
    },
  },
  watch: {
    "$route.query.q"(): void {
      this.onQueryChange();
    },
    "$route.query.page"(): void {
      this.updatePageFromQuery();
    },
    sort(): void {
      const query = String(this.$route.query.q)
        .replace(/((\s)?sort(:|=)\w*|$)/, ` sort:${this.sort}`)
        .trim();

      this.$router.push({
        path: this.$route.path,
        query: { q: query, page: "1" },
      });
    },
    order(): void {
      let query = String(this.$route.query.q)
        .replace(/((\s)?order(:|=)\w*|$)/g, "")
        .trim();

      if (this.order !== DEFAULT_ORDER) {
        query = `${query} order:${this.order}`;
      }

      this.$router.push({
        path: this.$route.path,
        query: { q: query },
      });
    },
  },
  async mounted(): Promise<void> {
    await this.onQueryChange();
  },
  methods: {
    async onQueryChange(): Promise<void> {
      this.loaded = false;

      const query = this.parseSearchQuery();
      this.updatePageFromQuery();

      if (!query) {
        this.loaded = true;
        return;
      }

      await this.updateSearchResults(query);

      this.loaded = true;
    },
    updatePageFromQuery(): void {
      this.page = Number(this.$route.query.page) || 1;
    },
    async updateSearchResults(query: string): Promise<void> {
      this.combos = [];
      this.message = "";
      this.errors = "";
      this.page = 1;
      this.$router.push({
        path: this.$route.path,
        query: { q: query },
      });

      const { message, sort, order, vendor, errors, combos } = await search(
        query
      );

      if (combos.length === 1) {
        this.redirecting = true;
        this.$router.replace({
          path: `/combo/${combos[0].commanderSpellbookId}/`,
          query: { q: query },
        });
        return;
      }

      this.message = message;
      this.sort = sort;
      this.vendor = vendor;
      this.order = order;
      this.errors = errors.map((e) => e.message).join(" ");
      this.combos = combos;
    },
    parseSearchQuery(): string {
      const query = this.$route.query.q;

      if (!query || typeof query !== "string") {
        return "";
      }

      return query;
    },
    navigateToPage(pagesToChange: number): void {
      this.page = this.page + pagesToChange;
      this.$router.push({
        path: this.$route.path,
        query: { q: this.$route.query.q, page: String(this.page) },
      });
    },
    goForward(): void {
      this.navigateToPage(1);
    },
    goBack(): void {
      this.navigateToPage(-1);
    },
  },
});
</script>

<style scoped>
/* Styles here */
</style>

// src/pages/search.tsx
import React from "react";
import PageWrapper from "../components/layout/PageWrapper/PageWrapper";
import SearchMessage from "../components/search/SearchMessage/SearchMessage";
import StyledSelect, {
  Option,
} from "../components/layout/StyledSelect/StyledSelect";
import { useRouter } from "next/router";
import {Variant} from "../lib/types";
import { DEFAULT_ORDER, DEFAULT_SORT } from "../lib/constants";
import SearchPagination from "../components/search/SearchPagination/SearchPagination";
import ComboResults from "../components/search/ComboResults/ComboResults";
import NoCombosFound from "../components/layout/NoCombosFound/NoCombosFound";
import SpellbookHead from "../components/SpellbookHead/SpellbookHead";
import {GetServerSideProps} from "next";
import {RequestService} from "../services/request.service";
import {PaginatedResponse} from "../types/api";

type Props = {
  combos: Variant[]
  count: number
  page: number
};

const SORT_OPTIONS: Option[] = [
  { value: "popularity", label: "Popularity" },
  { value: "identity_count", label: "Color Identity" },
  { value: "price", label: "Price" },
  {
    value: "cards_count",
    label: "# of Cards",
  },
  {
    value: "prerequisite_count",
    label: "# of Prerequisites",
  },
  {
    value: "steps_count",
    label: "# of Steps",
  },
  {
    value: "results_count",
    label: "# of Results",
  },
  {
    value: "created",
    label: "Date Created",
  },
  {
    value: "updated",
    label: "Date Updated",
  }
];

const ORDER_OPTIONS: Option[] = [
  { value: "auto", label: "Auto" },
  { value: "asc", label: "Ascending" },
  { value: "desc", label: "Descending" },
];

const PAGE_SIZE = 50
const Search: React.FC<Props> = ({combos, count, page}: Props) => {

  const router = useRouter();

  const sort = router.query.sort as string || DEFAULT_SORT;
  const order = router.query.order as string || DEFAULT_ORDER;


  const query = router.query.q;
  const parsedSearchQuery = (!query || typeof query !== "string") ? "" : query;


  const totalPages = Math.floor(count / PAGE_SIZE) + 1;

  const numberPage = Number(page) || 1
  const goForward = () => {
    router.push({ pathname: "/search/", query: { ...router.query, page: numberPage+1 } });
  };

  const goBack = () => {
    router.push({ pathname: "/search/", query: { ...router.query, page: numberPage-1 } });
  };

  const handleSortChange = (value: string) => {
    router.push({ pathname: "/search/", query: { ...router.query, sort: value, page: "1" } });
  };

  const handleOrderChange = (value: string) => {
    router.push({ pathname: "/search/", query: { ...router.query, order: value, page: "1" } });
  };

  const legalityMessage = (parsedSearchQuery.includes("legal:")) ? "" : " (legal:commander has been applied by default)"

  return (
    <PageWrapper>
      <SpellbookHead
        title="Commander Spellbook: Search Results"
        description="Search results for all EDH combos matching your query."
      />
      <div>
        <h1 className="sr-only">Search Results</h1>

        <SearchMessage
          message={`Showing ${count} results for query "${parsedSearchQuery}"${legalityMessage}`}
          errors={''}
          currentPage={page}
          totalPages={1}
          totalResults={1}
          maxNumberOfCombosPerPage={1}
        />

        {combos.length > 0 && (
          <div className="border-b border-light">
            <div className="container sm:flex flex-row items-center justify-center">
              <div className="mr-2 sm:mt-0 mt-2" aria-hidden="true">
                Sorted by
              </div>
              <StyledSelect
                value={sort}
                id="sort-combos-select"
                onChange={handleSortChange}
                selectBackgroundClassName="border-dark border-2 my-2 sm:mr-2"
                selectTextClassName="text-dark"
                label="Change how combos are sorted"
                options={SORT_OPTIONS}
              />
              <div className="mx-1 hidden sm:block" aria-hidden="true">
                :
              </div>
              <StyledSelect
                id="order-combos-select"
                value={order}
                onChange={handleOrderChange}
                selectBackgroundClassName="border-dark border-2 sm:m-2"
                selectTextClassName="text-dark"
                label="Change sort direction, ascending or descending"
                options={ORDER_OPTIONS}
              />
              <div className="flex-grow" />
              <SearchPagination
                currentPage={numberPage}
                totalPages={totalPages}
                aria-hidden="true"
                onGoForward={goForward}
                onGoBack={goBack}
              />
            </div>
          </div>
        )}

        <div className="container sm:flex flex-row">
          {combos.length > 0 ? (
            <div className="w-full">
              <ComboResults
                results={combos}
                sort={sort}
              />
              <SearchPagination
                currentPage={page}
                totalPages={totalPages}
                aria-hidden="true"
                onGoForward={goForward}
                onGoBack={goBack}
              />
            </div>
          ) : (
            <NoCombosFound  />
          )}
        </div>
      </div>
    </PageWrapper>
  );
};

export default Search;


export const getServerSideProps: GetServerSideProps = async (context) => {
  let query = `${context.query.q}`
  if (!query.includes('legal:')) query = `${query} legal:commander`

  const requestService = new RequestService(context)
  const order = context.query.order || DEFAULT_ORDER
  const sort = context.query.sort || DEFAULT_SORT
  const ordering = order === 'auto' ? sort : `${order === 'asc' ? '' : '-'}${sort}`
  const results = await requestService.get<PaginatedResponse<Variant>>(`https://backend.commanderspellbook.com/variants/?q=${query}&limit=${PAGE_SIZE}&offset=${((Number(context.query.page) || 1) - 1) * PAGE_SIZE}&ordering=${ordering}`)

  const backendCombos = results ? results.results : []

  return {
    props: {
      combos: backendCombos,
      count: results.count,
      page: context.query.page || 1,

    }
  }
}
