// frontend/components/combo/ComboList/ComboList.tsx
import styles from './comboList.module.scss'
import TextWithMagicSymbol from "../../layout/TextWithMagicSymbol/TextWithMagicSymbol";
import React, {useEffect, useState} from "react"
import PlaceholderText from "../../layout/PlaceholderText/PlaceholderText";

type Props = {
  title: string
  cardsInCombo?: string[]
  includeCardLinks?: boolean
  showNumbers?: boolean
  iterations: string[]
  id?: string
  className?: string
}

const ComboList = ({title, cardsInCombo = [], includeCardLinks, showNumbers, iterations, id, className}: Props) => {

  const [numberOfPlaceHolderItems, setNumberOfPlaceHolderItems] = useState(0)

  useEffect(() => {
    setNumberOfPlaceHolderItems(Math.floor(Math.random() * 5) + 2)
  }, [])

  return (
    <div id={id} className={`md:flex-1 my-4 w-full rounded overflow-hidden ${className}`}>
      <div className="pr-6 py-4">
        <h2 className={styles.comboListTitle}>{title}</h2>
        <ol className={`${styles.comboList} ${showNumbers && 'list-decimal'}`}>
          {iterations.map((item, index) => (
            <li key={`${title}-${index}`}>
              <TextWithMagicSymbol text={item} cardsInCombo={cardsInCombo} includeCardLinks={includeCardLinks} />
            </li>
          ))}
          {iterations.length === 0 && Array.from(Array(numberOfPlaceHolderItems).keys()).map((index) => (
            <li key={index}>
              <PlaceholderText maxLength={50} />
            </li>
          ))}
        </ol>
      </div>
    </div>
  )
}

export default ComboList

// components/combo/ComboList.vue
<template>
  <div class="md:flex-1 m-4 w-full rounded overflow-hidden">
    <div class="px-6 py-4">
      <div class="combo-list-title">{{ title }}</div>
      <ol class="combo-list" :class="{ 'list-decimal': showNumbers }">
        <li v-for="(item, index) in iterations" :key="title + '-' + index">
          <TextWithMagicSymbol :text="item" />
        </li>
        <div v-if="iterations.length === 0">
          <li v-for="n in Math.floor(Math.random() * 5) + 2">
            <PlaceholderText :maxLength="50" />
          </li>
        </div>
      </ol>
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from 'vue'
import TextWithMagicSymbol from '../TextWithMagicSymbol.vue'
import PlaceholderText from '../PlaceholderText.vue'

export default Vue.extend({
  components: {
    TextWithMagicSymbol,
    PlaceholderText,
  },
  props: {
    title: {
      type: String,
      default: '',
    },
    showNumbers: {
      type: Boolean,
      default: false,
    },
    iterations: {
      type: Array as PropType<string[]>,
      default() {
        return []
      },
    },
  },
})
</script>

<style scoped>
.combo-list-title {
  @apply font-bold text-xl mb-2;
}
.combo-list {
  @apply text-gray-700 text-base list-inside;
}
</style>
