// frontend/components/combo/ComboSidebarLinks/ShareComboButtons/ShareComboButtons.tsx
import styles from './shareComboButtons.module.scss'
import CopyComboLinkButton from "../CopyComboLinkButton/CopyComboLinkButton";
import ShareNetwork from "../ShareNetwork/ShareNetwork";

type Props = {
  comboLink: string
}

const ShareComboButtons = ({comboLink}: Props) => {

  const twitterUrl = `https://twitter.com/intent/tweet?text=Check out this combo!&url=${comboLink}&hashtags=commanderspellbook&via=CommanderSpell`
  const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${comboLink}&title=Check out this combo!&description=Check out this combo!&quote=&hashtag=%23commanderspellbook`
  const redditUrl = `https://www.reddit.com/submit?url=${comboLink}&title=Check out this combo!`

  return (
    <div className={`border-t border-gray pt-2 mt-1 ${styles.shareContainer}`}>
      <div className="flex">
        <CopyComboLinkButton className={`button ${styles.shareNetwork}`} comboLink={comboLink}>
          <div className={`${styles.linkIcon} ${styles.copyIcon}`}>
            <div className="sr-only">Copy to Clipboard</div>
          </div>
        </CopyComboLinkButton>

        <ShareNetwork url={twitterUrl} className={`button ${styles.shareNetwork}`} network="Twitter" >
          <div className={`${styles.linkIcon} ${styles.twitterIcon}`}/>
        </ShareNetwork>

        <ShareNetwork url={redditUrl} className={`button ${styles.shareNetwork}`} network="Reddit" >
          <div className={`${styles.linkIcon} ${styles.redditIcon}`}/>
        </ShareNetwork>

        <ShareNetwork url={facebookUrl} className={`button ${styles.shareNetwork}`} network="Facebook" >
          <div className={`${styles.linkIcon} ${styles.facebookIcon}`}/>
        </ShareNetwork>

        <div/> {/* This is a hack to make the buttons align to the right */}
      </div>
    </div>
  )
}

export default ShareComboButtons

// components/combo/ShareComboButtons.vue
<template>
  <div class="border-t border-gray pt-2 mt-1">
    <div class="flex">
      <CopyComboLinkButton
        v-tooltip.bottom="'Copy Combo Link to Clipboard'"
        class="button share-network"
        :combo-link="comboLink"
      >
        <div class="link-icon copy-icon">
          <div class="sr-only">Copy to Clipboard</div>
        </div>
      </CopyComboLinkButton>

      <ShareNetwork
        v-tooltip.bottom="'Share Combo on Twitter'"
        class="button share-network"
        network="Twitter"
        :url="comboLink"
        :title="text"
        :hashtags="hashtags"
        tag="button"
        twitter-user="CommanderSpell"
      >
        <div class="link-icon twitter-icon"></div>
      </ShareNetwork>

      <ShareNetwork
        v-tooltip.bottom="'Share Combo on Reddit'"
        class="button share-network"
        network="Reddit"
        :url="comboLink"
        :title="text"
        tag="button"
      >
        <div class="link-icon reddit-icon"></div>
      </ShareNetwork>

      <ShareNetwork
        v-tooltip.bottom="'Share Combo on Facebook'"
        class="button share-network"
        network="Facebook"
        :url="comboLink"
        :description="text"
        :hashtags="hashtags"
        tag="button"
      >
        <div class="link-icon facebook-icon"></div>
      </ShareNetwork>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import CopyComboLinkButton from "@/components/combo/CopyComboLinkButton.vue";

export default Vue.extend({
  components: {
    CopyComboLinkButton,
  },
  props: {
    comboLink: {
      type: String,
      default: "",
    },
  },
  computed: {
    hashtags(): string {
      return "commanderspellbook";
    },
    text(): string {
      return "Check out this combo!";
    },
  },
});
</script>

<style scoped>
.share-network.button {
  @apply flex items-center justify-center w-1/3 text-center mx-1 text-xl;
}

.share-network:first-child {
  @apply ml-0;
}

.share-network:last-child {
  @apply mr-0;
}

.share-network a {
  @apply no-underline;
}

.share-network:hover {
  @apply bg-link text-white border-link;
}

.link-icon {
  @apply bg-link h-6 w-6 m-auto;
}

.share-network:hover .link-icon {
  @apply bg-white;
}

.twitter-icon {
  -webkit-mask: url("~assets/svgs/twitter-square-brands.svg") no-repeat center;
  mask: url("~assets/svgs/twitter-square-brands.svg") no-repeat center;
}

.facebook-icon {
  -webkit-mask: url("~assets/svgs/facebook-square-brands.svg") no-repeat center;
  mask: url("~assets/svgs/facebook-square-brands.svg") no-repeat center;
}

.reddit-icon {
  -webkit-mask: url("~assets/svgs/reddit-square-brands.svg") no-repeat center;
  mask: url("~assets/svgs/reddit-square-brands.svg") no-repeat center;
}

.copy-icon {
  -webkit-mask: url("~assets/svgs/link-solid.svg") no-repeat center;
  mask: url("~assets/svgs/link-solid.svg") no-repeat center;
  @apply h-5 w-5;
}
</style>
