// components/syntax-guide/SearchGuide.vue
<template>
  <div :id="id" class="search-guide border-b-2 border-gray-400 w-full">
    <div class="container mt-6 mb-6 pb-4">
      <div class="mt-4 mb-4 flex-none text-center md:flex items-center">
        <ArtCircle
          :card-name="headingCardName"
          :artist="headingArtistName"
          class="mr-4 md:block hidden"
          :size="7"
        />
        <h2 class="heading-title">{{ heading }}</h2>
      </div>

      <div class="flex-none md:flex w-full">
        <div class="description w-full md:w-1/2 flex-grow pl-4 pr-4 md:pl-0">
          <slot />
        </div>

        <div
          class="search-snippets w-full md:w-1/2 flex-grow pl-4 pr-4 md:pr-4"
        >
          <SearchSnippet
            v-for="(snippet, index) in snippets"
            :key="index + '-' + snippet.search"
            :search="snippet.search"
            :description="snippet.description"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    heading: {
      type: String,
      default: "",
    },
    headingCardName: {
      type: String,
      default: "",
    },
    headingArtistName: {
      type: String,
      default: "",
    },
    snippets: {
      type: Array,
      default() {
        return [];
      },
    },
  },
  computed: {
    id() {
      return this.heading.toLowerCase().replace(" ", "-");
    },
  },
});
</script>

<style scoped>
@media (min-width: 768px) {
  .search-guide:nth-child(even) .description {
    @apply order-last pr-0 pl-4;
  }

  .search-guide:nth-child(even) .search-snippets {
    @apply pl-0 pr-4;
  }
}

.search-guide:last-child {
  @apply border-0;
}

code {
  @apply text-primary bg-gray-200 pl-1 pr-1;
}

.description p {
  @apply mb-4;
}
</style>

// frontend/components/layout/SearchGuide/SearchGuide.tsx
import React from "react";
import styles from "pages/syntax-guide.module.scss";
import ArtCircle, { ArtCircleProps } from "../ArtCircle/ArtCircle";
import SearchSnippet from "./SearchSnippet/SearchSnippet";
import Icon, {SpellbookIcon} from "../Icon/Icon";

type Props = {
  heading: string;
  headingCardName: ArtCircleProps["cardName"];
  snippets: { search: string; description: string }[];
  children: React.ReactNode;
  icon: SpellbookIcon,
  id?: string;
};

const SearchGuide: React.FC<Props> = ({
  heading,
  headingCardName,
  snippets,
  children,
  icon,
}: Props) => {
  const id = heading.toLowerCase().split(" / ")[0].replace(" ", "-");

  return (
    <div
      id={id}
      className={`${styles.searchGuide} ${styles.searchGuideContainer} border-b-2 border-gray-400 w-full`}
    >
      <div className="container mt-6 mb-6 pb-4">
        <div className="mt-4 mb-4 flex-none text-center md:flex items-center">
          <ArtCircle
            cardName={headingCardName}
            size={7}
            className="mr-4 md:block hidden"
          />
          <h2 className="heading-title"><Icon name={icon}/> {heading}</h2>
        </div>

        <div className="flex-none md:flex w-full">
          <div
            className={`${styles.description} w-full md:w-1/2 flex-grow pl-4 pr-4 md:pl-0`}
          >
            {children}
          </div>

          <div
            className={`${styles.searchSnippets} w-full md:w-1/2 flex-grow pl-4 pr-4 md:pr-4`}
          >
            {snippets.map((snippet, i) => (
              <SearchSnippet
                key={i}
                search={snippet.search}
                description={snippet.description}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default SearchGuide;
