// frontend/components/search/ComboResults/ComboResults.tsx
import styles from "./comboResults.module.scss";
import Link from "next/link";
import ColorIdentity from "../../layout/ColorIdentity/ColorIdentity";
import CardTooltip from "../../layout/CardTooltip/CardTooltip";
import {FormattedApiResponse, VendorValue} from "../../../lib/types";
import Card from "../../../lib/card";
import TextWithMagicSymbol from "../../layout/TextWithMagicSymbol/TextWithMagicSymbol";
import pluralize from "pluralize";

type Props = {
  missingDecklistCards?: Card[];
  results: FormattedApiResponse[];
  sort?: string;
  vendor?: VendorValue;
}

const getCardNames = (combo: FormattedApiResponse) =>
  combo.cards.map((card) => card.name);

const ComboResults = ({
  results,
  sort,
  vendor,
  missingDecklistCards = [],
}: Props) => {
  const isMissingInDecklistCards = (cardName: string) =>
    !!missingDecklistCards.find((card) => card.matchesNameExactly(cardName));

  const sortStatMessage = (combo: FormattedApiResponse) => {
    if (!sort) {
      return "";
    }

    if (sort === "popularity") {
      const numberOfDecks = combo.numberOfEDHRECDecks;

      if (!numberOfDecks) {
        return "No deck data (EDHREC)";
      }

      const deckString = pluralize("deck", numberOfDecks);

      return `${numberOfDecks} ${deckString} (EDHREC)`;
    }

    if (sort === "price" && vendor) {

      if (combo.cards.getPrice(vendor) === 0) {
        return "Price Unavailable";
      }
      return `$${combo.cards.getPriceAsString(vendor)}`;
    }

    switch (sort) {
      case "prerequisites":
      case "steps":
      case "results":
      case "cards":
        if (combo[sort].length === 1) {
          // remove the s in the sort word
          return `1 ${sort.slice(0, -1)}`;
        }
        return `${combo[sort].length} ${results.sort}`;
    }

    return "";
  };

  return (
    <div className={styles.comboResultsWrapper}>
      {results.map((combo) => (
        <Link
          href={`/combo/${combo.commanderSpellbookId}`}
          key={combo.commanderSpellbookId}
          className={`${styles.comboResult} w-full md:w-1/4`}
        >
          <div className="flex flex-col">
            <div className="flex items-center flex-grow flex-col bg-dark text-white">
              <ColorIdentity colors={combo.colorIdentity.colors} size="small" />
            </div>
            <div className="flex-grow border-b-2 border-light">
              <div className="py-1">
                <span className="sr-only">Cards in combo:</span>
                {getCardNames(combo).map((cardName) => (
                  <CardTooltip cardName={cardName} key={cardName}>
                    <div className="card-name pl-3 pr-3">
                      {isMissingInDecklistCards(cardName) ? (
                        <strong className="text-red-800">
                          {cardName} (not in deck)
                        </strong>
                      ) : (
                        <span>{cardName}</span>
                      )}
                    </div>
                  </CardTooltip>
                ))}
              </div>
            </div>
            <div className="flex-grow">
              <span className="sr-only">Results in combo:</span>
              {combo.results.map((result) => (
                <div key={result} className={`result pl-3 pr-3`}>
                  <TextWithMagicSymbol text={result} />
                </div>
              ))}
            </div>
          </div>
          <div className="flex items-center flex-grow flex-col">
            <div className="flex-grow" />
            {sortStatMessage(combo) && (
              <div className="sort-footer w-full py-1 text-center flex-shrink bg-dark text-white">
                {sortStatMessage(combo)}
              </div>
            )}
          </div>
        </Link>
      ))}
    </div>
  );
};

export default ComboResults;

// components/search/ComboResults.vue
<template>
  <div class="combo-results-wrapper">
    <nuxt-link
      v-for="r in results"
      ref="comboLinks"
      :key="'combo_' + r.commanderSpellbookId"
      :to="'/combo/' + r.commanderSpellbookId + '/'"
      class="combo-result w-full md:w-1/4"
    >
      <div class="flex flex-col">
        <div class="flex items-center flex-grow flex-col bg-dark text-white">
          <ColorIdentity :colors="r.colorIdentity.colors" size="small" />
        </div>
        <div class="flex-grow border-b-2 border-light">
          <div class="py-1">
            <span class="sr-only">Cards in combo:</span>
            <CardTooltip
              v-for="name in getCardNames(r)"
              :key="r.commanderSpellbookId + '_' + name"
              :card-name="name"
            >
              <div class="card-name pl-3 pr-3">
                {{ name }}
              </div>
            </CardTooltip>
          </div>
        </div>
        <div class="flex-grow">
          <span class="sr-only">Results in combo:</span>
          <!-- eslint-disable-next-line vue/require-v-for-key -->
          <div v-for="result in r.results" class="result pl-3 pr-3">
            <TextWithMagicSymbol :text="result" />
          </div>
        </div>
      </div>
      <div class="flex items-center flex-grow flex-col">
        <div class="flex-grow"></div>
        <div
          v-if="sortStatMessage(r)"
          class="sort-footer w-full py-1 text-center flex-shrink bg-dark text-white"
        >
          {{ sortStatMessage(r) }}
        </div>
      </div>
    </nuxt-link>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import CardTooltip from "@/components/CardTooltip.vue";
import TextWithMagicSymbol from "@/components/TextWithMagicSymbol.vue";
import ColorIdentity from "@/components/ColorIdentity.vue";
import { DEFAULT_VENDOR } from "@/lib/constants";
import type {
  FormattedApiResponse,
  SortValue,
  VendorValue,
} from "@/lib/api/types";

export default Vue.extend({
  components: {
    CardTooltip,
    ColorIdentity,
    TextWithMagicSymbol,
  },
  props: {
    sort: {
      type: String as PropType<SortValue>,
      default: "",
    },
    vendor: {
      type: String as PropType<VendorValue>,
      default: DEFAULT_VENDOR,
    },
    results: {
      type: Array as PropType<FormattedApiResponse[]>,
      default() {
        return [];
      },
    },
  },
  methods: {
    sortStatMessage(combo: FormattedApiResponse): string {
      if (!this.sort) {
        return "";
      }

      if (this.sort === "popularity") {
        if (!combo.numberOfEDHRECDecks) {
          return "No deck data (EDHREC)";
        }

        return `${combo.numberOfEDHRECDecks} ${
          this.$pluralize("deck", combo.numberOfEDHRECDecks)
        } (EDHREC)`;
      }

      if (this.sort === "price") {
        const vendor = this.vendor as VendorValue;

        if (combo.cards.getPrice(vendor) === 0) {
          return "Price Unavailable";
        }
        return `$${combo.cards.getPriceAsString(vendor)}`;
      }

      switch (this.sort) {
        case "prerequisites":
        case "steps":
        case "results":
        case "cards":
          if (combo[this.sort].length === 1) {
            // remove the s in the sort word
            return `1 ${this.sort.slice(0, -1)}`;
          }
          return `${combo[this.sort].length} ${this.sort}`;
      }

      return "";
    },
    getCardNames(combo: FormattedApiResponse): string[] {
      return combo.cards.map((c) => c.name);
    },
  },
});
</script>

<style scoped>
a {
  @apply no-underline text-dark;
}

.combo-results-wrapper {
  @apply flex flex-wrap justify-center;
}

.combo-result {
  @apply max-w-lg mx-0 my-2 rounded border-2 border-dark flex-grow flex flex-col content-center;
}

@media (min-width: 768px) {
  .combo-result {
    @apply m-2;
  }

  .combo-result:nth-child(3n + 3) {
    @apply mr-0;
  }

  .combo-result:nth-child(3n + 1) {
    @apply ml-0;
  }
}
</style>
