// frontend/components/SearchBar.vue
<template>
  <div class="outer-container">
    <form class="main-search-input-container" @submit.prevent="onSubmit">
      <nuxt-link v-if="!onHomePage" to="/" class="block mr-2 flex-shrink py-1">
        <div class="mr-1">
          <img
            src="~/assets/images/gear.svg"
            alt="Go to home page"
            class="w-8 inline-block"
          />
        </div>
      </nuxt-link>

      <div class="flex flex-grow items-center">
        <div
          v-if="!onHomePage"
          class="search-input-icon"
          aria-hidden="true"
          @click="focusSearch"
        ></div>
        <label
          for="search-bar-input"
          class="sr-only text-white"
          aria-hidden="true"
          >Combo Search</label
        >
        <input
          id="search-bar-input"
          ref="searchInput"
          v-model="query"
          type="text"
          class="main-search-input"
          :class="inputClasses"
          name="q"
          :placeholder="`Search ${numberOfCombos} EDH combos`"
          autocomplete="off"
          autocapitalize="none"
          autocorrect="off"
          spellcheck="false"
          :autofocus="onHomePage"
        />
      </div>
      <div
        v-if="!onHomePage"
        class="flex flex-shrink flex-row items-center desktop-menu"
      >
        <button
          id="search-bar-menu-button"
          type="button"
          class="mobile-menu-button"
          @click="toggleMenu"
        >
          <div class="menu-icon link-icon" aria-hidden="true"></div>
          <div class="sr-only">Menu</div>
        </button>
        <nuxt-link to="/advanced-search/" class="hidden md:flex menu-link">
          <div class="advanced-search-icon link-icon" aria-hidden="true"></div>
          Advanced
        </nuxt-link>
        <nuxt-link to="/syntax-guide/" class="hidden md:flex menu-link">
          <div class="syntax-guide-icon link-icon" aria-hidden="true"></div>
          Syntax
        </nuxt-link>
        <RandomButton :query="query" class="hidden md:flex menu-link">
          <div class="random-icon link-icon" aria-hidden="true"></div>
          Random
        </RandomButton>
      </div>
    </form>
    <div
      v-if="!onHomePage && showMobileMenu"
      class="md:hidden flex flex-wrap flex-row text-center mt-2 py-4 border-t border-light text-light"
      @click="toggleMenu"
    >
      <nuxt-link to="/advanced-search/" class="mobile-menu-button">
        <div class="advanced-search-icon link-icon" aria-hidden="true"></div>
        Advanced
      </nuxt-link>
      <nuxt-link to="/syntax-guide/" class="mobile-menu-button">
        <div class="syntax-guide-icon link-icon" aria-hidden="true"></div>
        Syntax
      </nuxt-link>
      <RandomButton :query="query" class="mobile-menu-button">
        <div class="random-icon link-icon" aria-hidden="true"></div>
        Random
      </RandomButton>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import RandomButton from "@/components/RandomButton.vue";
import getAllCombos from "@/lib/api/get-all-combos";

export default Vue.extend({
  components: {
    RandomButton,
  },
  props: {
    onHomePage: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      showMobileMenu: false,
      numberOfCombos: "thousands of",
    };
  },
  async fetch() {
    await this.lookupNumberOfCombos();
  },
  computed: {
    query: {
      get(): string {
        return this.$store.state.query.value;
      },
      set(value: string): void {
        this.$store.commit("query/change", value);
      },
    },
    inputClasses(): string {
      if (this.onHomePage) {
        return "text-2xl text-center";
      }
      return "pl-8 -ml-6";
    },
  },
  watch: {
    "$route.query.q"(): void {
      this.setQueryFromUrl();
    },
  },
  mounted() {
    this.setQueryFromUrl();
  },
  methods: {
    focusSearch(): void {
      (this.$refs.searchInput as HTMLInputElement).focus();
    },
    async lookupNumberOfCombos(): Promise<void> {
      const combos = await getAllCombos();

      this.numberOfCombos = String(combos.length);
    },
    setQueryFromUrl(): void {
      const query = this.$route.query.q;

      if (typeof query === "string") {
        this.query = query;
      } else {
        this.query = "";
      }
    },
    toggleMenu(): void {
      this.showMobileMenu = !this.showMobileMenu;
    },
    onSubmit(): void {
      if (!this.query.trim()) {
        return;
      }

      this.$gtag.event("search", {
        search_term: this.query,
      });

      this.$router.push({
        path: "/search/",
        query: {
          q: this.query,
        },
      });
    },
  },
});
</script>

<style scoped>
.outer-container {
  @apply mx-auto;
}

a {
  @apply text-white no-underline;
}

.main-search-input-container {
  @apply flex m-auto h-full;
}

.main-search-input {
  @apply w-full h-full appearance-none block py-2 bg-transparent text-white leading-tight;
}

.main-search-input:focus {
  @apply outline-none bg-white text-dark;
}

.link-icon {
  @apply bg-white h-4 w-4 mr-2;
}

.menu-icon {
  mask: url("~assets/svgs/bars-solid.svg") no-repeat center;
  @apply mr-0;
}

.advanced-search-icon {
  mask: url("~assets/svgs/columns-solid.svg") no-repeat center;
}

.syntax-guide-icon {
  mask: url("~assets/svgs/question-solid.svg") no-repeat center;
}

.profile-icon {
  mask: url("~assets/svgs/user-circle-solid.svg") no-repeat center;
}

.random-icon {
  mask: url("~assets/svgs/random-solid.svg") no-repeat center;
}

.search-input-icon {
  mask: url("~assets/svgs/search-solid.svg") no-repeat center;
  @apply bg-light w-4 h-4 mt-1 z-10 cursor-pointer;
}

.search-input-icon:hover {
  @apply bg-light;
}

.menu-link {
  @apply items-center flex-row px-4 text-white border-l border-white;
}

.menu-link:last-of-type {
  @apply pr-0;
}

.menu-link:hover {
  @apply text-light;
}

.menu-link:hover .link-icon {
  @apply bg-light;
}

.mobile-menu-button {
  @apply flex flex-row flex-grow items-center w-1/3 rounded py-1 px-2 border border-light mx-2;
}

.mobile-menu-button:hover {
  @apply border-light text-light;
}

.mobile-menu-button:hover .link-icon {
  @apply bg-light;
}

.mobile-menu-button:nth-child(even),
.mobile-menu-button:last-of-type {
  @apply mr-0;
}

.mobile-menu-button:nth-child(odd) {
  @apply ml-0;
}

.mobile-menu-button:nth-child(n + 3) {
  @apply mt-2;
}

@media (min-width: 640px) {
  #search-bar-menu-button {
    @apply hidden;
  }
}

@media (max-width: 1280px) {
  .flex.flex-shrink.flex-row.items-center.desktop-menu a div {
    display: none;
  }
}
</style>

// frontend/components/SearchBar/SearchBar.tsx
import React, { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import styles from "./searchBar.module.scss";
import { useRouter } from "next/router";
import getAllCombos from "../../lib/get-all-combos";

type Props = {
  onHomepage?: boolean;
  className?: string;
};

const SearchBar: React.FC<Props> = ({ onHomepage, className }: Props) => {
  const router = useRouter();

  const [mobileMenuIsOpen, setMobileMenuIsOpen] = useState(false);
  const [inputValue, setInputValue] = useState(router.query.q);
  const [numberOfCombos, setNumberOfCombos] = useState(0);

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (typeof inputValue === "string" && inputValue.trim()) {
      router.push(`/search/?q=${inputValue}`);
    }
  };

  useEffect(() => {
    setInputValue(router.query.q);
    getAllCombos().then((combos) => {
      setNumberOfCombos(combos.length);
    });
  }, [router.query.q]);

  return (
    <div className={`${styles.outerContainer} ${className}`}>
      <form onSubmit={handleSubmit} className={styles.mainSearchInputContainer}>
        {!onHomepage && (
          <Link href="/" className="block mr-2 flex-shrink py-1">
            <div className="mr-1">
              <img
                src="/images/gear.svg"
                alt="Go to home page"
                className="w-8 inline-block"
              />
            </div>
          </Link>
        )}

        <div className="flex flex-grow items-center">
          {!onHomepage && (
            <div
              className={styles.searchInputIcon}
              aria-hidden="true"
              onClick={() => "focusSearch"}
            />
          )}
          <label
            htmlFor="search-bar-input"
            className="sr-only text-white"
            aria-hidden="true"
          >
            Combo Search
          </label>
          <input
            value={inputValue}
            name="q"
            onChange={(e) => setInputValue(e.target.value)}
            placeholder={`Search ${
              numberOfCombos ? numberOfCombos + " " : ""
            }EDH combos`}
            id="search-bar-input"
            type="text"
            className={`${styles.mainSearchInput} ${
              onHomepage ? "text-2xl text-center" : "pl-8 -ml-6"
            }`}
          />
        </div>

        {!onHomepage && (
          <div className="flex flex-shrink flex-row items-center desktop-menu">
            <button
              id="search-bar-menu-button"
              type="button"
              className={styles.mobileMenuButton}
              onClick={() => setMobileMenuIsOpen(!mobileMenuIsOpen)}
            >
              <div
                className={`${styles.menuIcon} ${styles.linkIcon}`}
                aria-hidden="true"
              />
              <div className="sr-only">Menu</div>
            </button>
            <Link
              href="/advanced-search/"
              className={`hidden md:flex ${styles.menuLink}`}
            >
              <div
                className={`${styles.advancedSearchIcon} ${styles.linkIcon}`}
                aria-hidden="true"
              />
              Advanced
            </Link>
            <Link
              href="/syntax-guide/"
              className={`hidden md:flex ${styles.menuLink}`}
            >
              <div
                className={`${styles.syntaxGuideIcon} ${styles.linkIcon}`}
                aria-hidden="true"
              />
              Syntax
            </Link>
            <Link
              href="/random"
              className={`hidden md:flex ${styles.menuLink}`}
            >
              <div
                className={`${styles.randomIcon} ${styles.linkIcon}`}
                aria-hidden="true"
              />
              Random
            </Link>
          </div>
        )}
      </form>

      {!onHomepage && mobileMenuIsOpen && (
        <div
          className="md:hidden flex flex-wrap flex-row text-center mt-2 py-4 border-t border-light text-light"
          onClick={() => setMobileMenuIsOpen(!mobileMenuIsOpen)}
        >
          <Link href="/advanced-search/" className={styles.mobileMenuButton}>
            <div
              className={`${styles.advancedSearchIcon} ${styles.linkIcon}`}
              aria-hidden="true"
            />
            Advanced
          </Link>
          <Link href="/syntax-guide/" className={styles.mobileMenuButton}>
            <div
              className={`${styles.syntaxGuideIcon} ${styles.linkIcon}`}
              aria-hidden="true"
            />
            Syntax
          </Link>
          <Link href="/random" className={styles.mobileMenuButton}>
            <div
              className={`${styles.randomIcon} ${styles.linkIcon}`}
              aria-hidden="true"
            />
            Random
          </Link>
        </div>
      )}
    </div>
  );
};

export default SearchBar;
