// frontend/components/advanced-search/RadioSearchInput.vue
<template>
  <div>
    <div class="font-semibold">{{ label }}</div>

    <fieldset class="flex flex-col">
      <legend class="sr-only" aria-hidden="true">
        Choose settings for {{ label }}
      </legend>
      <label
        v-for="(option, index) in options"
        :key="`${label}-radio-input-${index}`"
        :for="label + '-radio-input-' + index"
        class="radio-wrapper sm:inline-flex items-center mt-3"
      >
        <input
          :id="label + '-radio-input-' + index"
          type="radio"
          :name="formName"
          class="h-5 w-5"
          :checked="checkedValue === option.value"
          :value="option.value"
          @change="updateRadio(option.value)"
        /><span class="ml-2 text-dark">{{ option.label }}</span>
      </label>
    </fieldset>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";

export default Vue.extend({
  props: {
    checkedValue: {
      type: String,
      default: "",
    },
    options: {
      type: Array as PropType<{ value: string; label: string }[]>,
      default() {
        return [];
      },
    },
    formName: {
      type: String,
      default: "",
    },
    label: {
      type: String,
      default: "",
    },
  },
  methods: {
    updateRadio(value: string) {
      this.$emit("update-radio", value);
    },
  },
});
</script>

// src/components/advancedSearch/RadioSearchInput/RadioSearchInput.tsx
import React, { useState } from "react";
import Icon, { SpellbookIcon } from "../../layout/Icon/Icon";

type Props = {
  checkedValue: string;
  options: Array<{ value: string; label: string }>;
  formName: string;
  label: string;
  labelIcon?: SpellbookIcon;
  onChange?: (_value: string) => void;
};

const RadioSearchInput: React.FC<Props> = ({ checkedValue, options, formName, label, labelIcon, onChange }) => {
  const [localValue, setLocalValue] = useState<string>(checkedValue);

  const handleChange = (value: string) => {
    setLocalValue(value);
    onChange && onChange(value);
  };

  return (
    <div>
      <label className="font-semibold">
        {labelIcon && <Icon name={labelIcon} />} {label}
      </label>
      <fieldset className="flex flex-wrap gap-7">
        <legend className="sr-only" aria-hidden="true">
          Choose settings for {label}
        </legend>
        {options.map((option, index) => (
          <label
            key={`${label}-radio-input-${index}`}
            htmlFor={`${label}-radio-input-${index}`}
            className="radio-wrapper sm:inline-flex items-center mt-3"
          >
            <input
              id={`${label}-radio-input-${index}`}
              type="radio"
              name={formName}
              className="h-5 w-5"
              checked={localValue === option.value}
              value={option.value}
              onChange={() => handleChange(option.value)}
            />
            <span className="ml-2 text-dark">{option.label}</span>
          </label>
        ))}
      </fieldset>
    </div>
  );
};

export default RadioSearchInput;
