// src/components/search/ComboResults/ComboResults.tsx
import styles from "./comboResults.module.scss";
import Link from "next/link";
import ColorIdentity from "../../layout/ColorIdentity/ColorIdentity";
import CardTooltip from "../../layout/CardTooltip/CardTooltip";
import {Variant, VendorValue} from "../../../lib/types";
import TextWithMagicSymbol from "../../layout/TextWithMagicSymbol/TextWithMagicSymbol";
import pluralize from "pluralize";
import {Deck} from "../../../lib/decklist-parser";

type ResultProps = {
  deck?: Deck; // If passed in, will highlight cards in the combo that are not in the deck
  combo: Variant;
  sort?: string;
  cards?: string[]
  newTab?: boolean;
}
export const ComboResult = ({combo, deck, sort, cards=[], newTab}: ResultProps) => {

  const sortStatMessage = (combo: Variant) => {
    if (!sort) {
      return "";
    }

    if (sort === "popularity") {
      const numberOfDecks = combo.popularity;

      if (numberOfDecks === null || numberOfDecks === undefined) {
        return "No deck data (EDHREC)";
      }

      const deckString = pluralize("deck", numberOfDecks);

      return `${numberOfDecks} ${deckString} (EDHREC)`;
    }

    if (sort.startsWith("price")) {
      if (sort.includes("cardkingdom")) {
        return `$${combo.prices.cardkingdom}`;
      }
      if (sort.includes("cardmarket")) {
        return `€${combo.prices.cardmarket}`;
      }
      return `$${combo.prices.tcgplayer}`;
    }

    // switch (sort) {
    //   case "uses":
    //   case "steps":
    //   case "produces":
    //     if (combo[sort].length === 1) {
    //       // remove the s in the sort word
    //       return `1 ${sort.slice(0, -1)}`;
    //     }
    //     return `${combo[sort].length} ${results.sort}`;
    // }

    return "";
  };

  const prereqCount = combo.otherPrerequisites ? combo.otherPrerequisites.split(".").filter(s => s.trim().length).length : 0;

  return (
    <Link
      href={`/combo/${combo.id}`}
      key={combo.id}
      className={`${styles.comboResult} w-full md:w-1/4`}
      rel={newTab ? "noopener noreferrer" : undefined}
      target={newTab ? "_blank" : undefined}
    >
      <div className="flex flex-col">
        <div className={`flex items-center flex-grow flex-col ${combo.status === "OK" ? "bg-dark" : combo.status === "E" ? "bg-[#888888]" : "bg-light"} text-white`}>
          <ColorIdentity colors={Array.from(combo.identity)} size="small" />
        </div>
        <div className="flex-grow border-b-2 border-light">
          <div className="py-1">
            <span className="sr-only">Cards in combo:</span>
            {combo.uses.map(({card}) => (
              <CardTooltip cardName={card.name} key={card.name}>
                <div className="card-name pl-3 pr-3">
                  {(deck && !cards.includes(card.name.toLowerCase())) ? (
                    <strong className="text-red-800">
                      {card.name} (not in deck)
                    </strong>
                  ) : (
                    <span>{card.name}</span>
                  )}
                </div>
              </CardTooltip>
            ))}
            {combo.requires.length > 0 && (
              <div className="prerequisites pl-3 pr-3">
                <span className="text-gray-500">+{combo.requires.length} other card{combo.requires.length > 1 ? "s" : ""}</span>
              </div>
            )}
            {prereqCount > 0 && (
              <div className="prerequisites pl-3 pr-3">
                <span className="text-gray-500">+{prereqCount} other prerequisite{prereqCount > 1 ? "s" : ""}</span>
              </div>
            )}
          </div>
        </div>
        <div className="flex-grow">
          <span className="sr-only">Results in combo:</span>
          {combo.produces.map((result) => (
            <div key={result.name ?? result.feature.name} className={`result pl-3 pr-3`}>
              <TextWithMagicSymbol text={result.name ?? result.feature.name} />
            </div>
          ))}
        </div>
      </div>
      <div className="flex items-center flex-grow flex-col">
        <div className="flex-grow" />
        {sortStatMessage(combo) && (
          <div className="sort-footer w-full py-1 text-center flex-shrink bg-dark text-white">
            {sortStatMessage(combo)}
          </div>
        )}
      </div>
    </Link>
  )
}

type Props = {
  deck?: Deck; // If passed in, will highlight cards in the combo that are not in the deck
  results: Variant[];
  sort?: string;
  vendor?: VendorValue;
}

const ComboResults = ({
  results,
  sort,
  deck,
}: Props) => {


  const cards = deck?.cards.map((card) => card.toLowerCase()) ?? [];

  return (
    <div className={styles.comboResultsWrapper}>
      {results.map((combo) => (
        <ComboResult combo={combo} cards={cards} deck={deck} sort={sort} key={combo.id} />
      ))}
    </div>
  );
};

export default ComboResults;

// frontend/components/search/ComboResults.vue
<template>
  <div class="combo-results-wrapper">
    <nuxt-link
      v-for="r in results"
      ref="comboLinks"
      :key="'combo_' + r.commanderSpellbookId"
      :to="'/combo/' + r.commanderSpellbookId + '/'"
      class="combo-result w-full md:w-1/4"
    >
      <div class="flex flex-col">
        <div class="flex items-center flex-grow flex-col bg-dark text-white">
          <ColorIdentity :colors="r.colorIdentity.colors" size="small" />
        </div>
        <div class="flex-grow border-b-2 border-light">
          <div class="py-1">
            <span class="sr-only">Cards in combo:</span>
            <CardTooltip
              v-for="name in getCardNames(r)"
              :key="r.commanderSpellbookId + '_' + name"
              :card-name="name"
            >
              <div class="card-name pl-3 pr-3">
                <strong v-if="isMissingInDecklist(name)" class="text-red-800"
                  >{{ name }} (not in deck)</strong
                >
                <span v-else>{{ name }}</span>
              </div>
            </CardTooltip>
          </div>
        </div>
        <div class="flex-grow">
          <span class="sr-only">Results in combo:</span>
          <!-- eslint-disable-next-line vue/require-v-for-key -->
          <div v-for="result in r.results" class="result pl-3 pr-3">
            <TextWithMagicSymbol :text="result" />
          </div>
        </div>
      </div>
      <div class="flex items-center flex-grow flex-col">
        <div class="flex-grow"></div>
        <div
          v-if="sortStatMessage(r)"
          class="sort-footer w-full py-1 text-center flex-shrink bg-dark text-white"
        >
          {{ sortStatMessage(r) }}
        </div>
      </div>
    </nuxt-link>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import CardTooltip from "@/components/CardTooltip.vue";
import TextWithMagicSymbol from "@/components/TextWithMagicSymbol.vue";
import ColorIdentity from "@/components/ColorIdentity.vue";
import { DEFAULT_VENDOR } from "@/lib/constants";
import type {
  FormattedApiResponse,
  SortValue,
  VendorValue,
} from "@/lib/api/types";
import type Card from "@/lib/api/models/card";

export default Vue.extend({
  components: {
    CardTooltip,
    ColorIdentity,
    TextWithMagicSymbol,
  },
  props: {
    sort: {
      type: String as PropType<SortValue>,
      default: "",
    },
    vendor: {
      type: String as PropType<VendorValue>,
      default: DEFAULT_VENDOR,
    },
    results: {
      type: Array as PropType<FormattedApiResponse[]>,
      default() {
        return [];
      },
    },
    missingDecklistCards: {
      type: Array as PropType<Card[]>,
      default() {
        return [];
      },
    },
  },
  methods: {
    isMissingInDecklist(name: string): boolean {
      const isMissing = this.missingDecklistCards.find((card) => {
        return card.matchesNameExactly(name);
      });

      return Boolean(isMissing);
    },
    sortStatMessage(combo: FormattedApiResponse): string {
      if (!this.sort) {
        return "";
      }

      if (this.sort === "popularity") {
        const numberOfDecks = combo.numberOfEDHRECDecks;

        if (!numberOfDecks) {
          return "No deck data (EDHREC)";
        }

        const deckString = this.$pluralize("deck", numberOfDecks);

        return `${numberOfDecks} ${deckString} (EDHREC)`;
      }

      if (this.sort === "price") {
        const vendor = this.vendor as VendorValue;

        if (combo.cards.getPrice(vendor) === 0) {
          return "Price Unavailable";
        }
        return `$${combo.cards.getPriceAsString(vendor)}`;
      }

      switch (this.sort) {
        case "prerequisites":
        case "steps":
        case "results":
        case "cards":
          if (combo[this.sort].length === 1) {
            // remove the s in the sort word
            return `1 ${this.sort.slice(0, -1)}`;
          }
          return `${combo[this.sort].length} ${this.sort}`;
      }

      return "";
    },
    getCardNames(combo: FormattedApiResponse): string[] {
      return combo.cards.map((c) => c.name);
    },
  },
});
</script>

<style scoped>
a {
  @apply no-underline text-dark;
}

.combo-results-wrapper {
  @apply flex flex-wrap justify-center;
}

.combo-result {
  @apply max-w-lg mx-0 my-2 rounded border-2 border-dark flex-grow flex flex-col content-center;
}

@media (min-width: 768px) {
  .combo-result {
    @apply m-2;
  }

  .combo-result:nth-child(3n + 3) {
    @apply mr-0;
  }

  .combo-result:nth-child(3n + 1) {
    @apply ml-0;
  }
}
</style>
