// components/advanced-search/AutocompleteInput.vue
<template>
  <!-- adapted from https://www.digitalocean.com/community/tutorials/vuejs-vue-autocomplete-component -->
  <div class="autocomplete-container">
    <label class="sr-only" aria-hidden="true" :for="inputId">{{ label }}</label>
    <input
      :id="inputId"
      ref="input"
      v-model="localValue"
      type="text"
      :placeholder="placeholder"
      class="input"
      :class="{
        [inputClass]: true,
        'border-danger': hasError,
      }"
      autocomplete="off"
      autocapitalize="none"
      autocorrect="off"
      spellcheck="false"
      @input="onChange"
      @blur="onBlur"
      @keydown.down="onArrowDown"
      @keydown.up="onArrowUp"
      @keydown.enter="onEnter"
      @keydown.tab="onTab"
      @keydown.escape="close"
    />
    <div
      role="status"
      aria-live="polite"
      class="sr-only autocomplete-sr-message"
    >
      {{ screenReaderSelectionText }}
    </div>
    <ul
      v-show="matchingAutocompleteOptions.length > 0"
      ref="autocompleteResults"
      class="autocomplete-results"
    >
      <li
        v-for="(item, i) in matchingAutocompleteOptions"
        :key="i"
        :class="{ 'is-active': i === arrowCounter }"
        class="autocomplete-result"
        @click="onClick(item)"
        @mouseover="onAutocompleteItemHover(i)"
      >
        <TextWithMagicSymbol :text="item.label" />
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import TextWithMagicSymbol from "@/components/TextWithMagicSymbol.vue";

import normalizeStringInput from "@/lib/api/normalize-string-input";

type AutoCompleteOption = { value: string; label: string; alias?: RegExp };

const MAX_NUMBER_OF_MATCHING_RESULTS = 20;
const AUTOCOMPLETE_DELAY = 150;
const BLUR_CLOSE_DELAY = 1000;

export default Vue.extend({
  components: {
    TextWithMagicSymbol,
  },
  props: {
    value: {
      type: String,
      default: "",
    },
    inputClass: {
      type: String,
      default: "",
    },
    autocompleteOptions: {
      type: Array as PropType<AutoCompleteOption[]>,
      default() {
        return [];
      },
    },
    inputId: {
      type: String,
      default: "",
    },
    placeholder: {
      type: String,
      default: "",
    },
    label: {
      type: String,
      default: "",
    },
    hasError: {
      type: Boolean,
      default: false,
    },
    useValueForInput: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      arrowCounter: -1,
      autocompleteTimeout: 0 as unknown as ReturnType<typeof setTimeout>,
      matchingAutocompleteOptions: [] as { value: string; label: string }[],
    };
  },
  computed: {
    localValue: {
      get(): string {
        return this.value;
      },
      set(value: string): void {
        this.$emit("input", value);
      },
    },
    active(): boolean {
      return this.autocompleteOptions.length > 0;
    },
    screenReaderSelectionText(): string {
      if (this.matchingAutocompleteOptions.length === 0 || !this.value) {
        return "";
      }
      const total = this.matchingAutocompleteOptions.length;
      const option = this.matchingAutocompleteOptions[this.arrowCounter];

      if (!option) {
        return `${total} match${total > 1 ? "es" : ""} found for ${
          this.value
        }. Use the up and down arrow keys to browse the options. Use the enter or tab key to choose a selection or continue typing to narrow down the options.`;
      }

      return `${option.label} (${this.arrowCounter + 1}/${total})`;
    },
  },
  methods: {
    onChange(): void {
      if (!this.active) {
        return;
      }
      this.lookupAutocomplete();
    },
    onBlur(): void {
      if (!this.active) {
        return;
      }

      // this needs to be in a timeout so the action
      // to choose can still reference the autocomplete
      // options, if it's not in a timeout, clicking
      // the option causes the blur event to fire first,
      // and prevents the click event from even happening
      // because the menu closes before the click occurs
      setTimeout(() => {
        this.close();
      }, BLUR_CLOSE_DELAY);
    },
    onAutocompleteItemHover(index: number): void {
      this.arrowCounter = index;
    },
    choose(choice: AutoCompleteOption): void {
      const value = this.useValueForInput ? choice.value : choice.label;
      this.$emit("input", value);
      this.close();
    },
    close(): void {
      const ref = this.$refs.autocompleteResults as HTMLElement;

      if (ref) {
        ref.scrollTop = 0;
      }

      this.arrowCounter = -1;
      this.matchingAutocompleteOptions = [];
    },
    onArrowDown(e: KeyboardEvent): void {
      e.preventDefault();

      if (this.arrowCounter + 1 < this.matchingAutocompleteOptions.length) {
        this.arrowCounter = this.arrowCounter + 1;
      }

      this.scrollToSelection();
    },
    onArrowUp(e: KeyboardEvent): void {
      e.preventDefault();

      if (this.arrowCounter >= 0) {
        this.arrowCounter = this.arrowCounter - 1;
      }

      this.scrollToSelection();
    },
    scrollToSelection(): void {
      const ref = this.$refs.autocompleteResults as HTMLElement;
      const nodes = ref.querySelectorAll("li");
      const li = nodes[this.arrowCounter];

      if (!li || !ref) {
        return;
      }
      ref.scrollTop = li.offsetTop - 50;
    },
    onEnter(e: KeyboardEvent): void {
      const choice = this.matchingAutocompleteOptions[this.arrowCounter];

      if (!choice) {
        // allow the form to be submitted if enter was used without a selection
        return;
      }

      e.preventDefault();

      this.choose(choice);
    },
    onTab(): void {
      const choice = this.matchingAutocompleteOptions[this.arrowCounter];

      if (choice) {
        this.choose(choice);
      }
    },
    onClick(item: AutoCompleteOption) {
      this.choose(item);
      const input = this.$refs.input as HTMLInputElement;

      if (input) {
        input.focus();
      }
    },
    findAllMatches(normalizedValue: string) {
      return this.autocompleteOptions.filter((option) => {
        const mainMatch = option.value.includes(normalizedValue);

        return (
          mainMatch || (option.alias && normalizedValue.match(option.alias))
        );
      });
    },
    findBestMatches(
      totalOptions: AutoCompleteOption[],
      normalizedValue: string
    ) {
      totalOptions.sort((a, b) => {
        const indexA = a.value.indexOf(normalizedValue);
        const indexB = b.value.indexOf(normalizedValue);

        if (indexA === indexB) {
          return 0;
        }

        if (indexA === -1) {
          return 1;
        }
        if (indexB === -1) {
          return -1;
        }

        if (indexA < indexB) {
          return -1;
        } else if (indexB < indexA) {
          return 1;
        }

        return 0;
      });

      return totalOptions.slice(0, MAX_NUMBER_OF_MATCHING_RESULTS);
    },
    createAutocompleteTimeout(): ReturnValue<typeof setTimeout> {
      return setTimeout(() => {
        if (!this.value) {
          this.close();
          return;
        }

        const normalizedValue = normalizeStringInput(this.value);
        this.matchingAutocompleteOptions = [];

        const totalOptions = this.findAllMatches(normalizedValue);

        this.matchingAutocompleteOptions = this.findBestMatches(
          totalOptions,
          normalizedValue
        );
      }, AUTOCOMPLETE_DELAY);
    },
    lookupAutocomplete(): void {
      if (!this.active) {
        return;
      }

      if (!this.value) {
        this.close();
        return;
      }

      if (this.autocompleteTimeout) {
        clearTimeout(this.autocompleteTimeout);
      }
      this.autocompleteTimeout = this.createAutocompleteTimeout();
    },
  },
});
</script>

<style scoped>
.autocomplete-container {
  @apply relative flex-grow;
}

.autocomplete-results {
  @apply p-0 m-0 bg-white border border-light overflow-auto max-h-48 absolute w-full z-10;
}

.autocomplete-result {
  @apply text-left p-2 cursor-pointer;
}

.autocomplete-result.is-active {
  @apply bg-link text-white;
}
</style>

// frontend/components/advancedSearch/AutocompleteInput/AutocompleteInput.tsx
import React, { KeyboardEventHandler } from "react";
import styles from "./autocompleteInput.module.scss";
import { useState } from "react";
import normalizeStringInput from "../../../lib/normalizeStringInput";
import TextWithMagicSymbol from "../../layout/TextWithMagicSymbol/TextWithMagicSymbol";

const MAX_NUMBER_OF_MATCHING_RESULTS = 20;
const AUTOCOMPLETE_DELAY = 150;
const BLUR_CLOSE_DELAY = 1000;

type AutoCompleteOption = { value: string; label: string; alias?: RegExp };

type Props = {
  value: string;
  inputClassName?: string;
  autocompleteOptions: AutoCompleteOption[];
  inputId: string;
  placeholder?: string;
  label?: string;
  matchAgainstOptionLabel?: boolean;
  hasError?: boolean;
  useValueForInput?: boolean;
  onChange?: (value: string) => void;
};

const AutocompleteInput: React.FC<Props> = ({
  value,
  inputClassName,
  autocompleteOptions,
  inputId,
  label,
  matchAgainstOptionLabel,
  useValueForInput,
  placeholder,
  hasError,
  onChange,
}: Props) => {
  const resultsRef = React.useRef<HTMLUListElement>(null);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const timeoutRef = React.useRef<ReturnType<typeof setTimeout>>();
  const [localValue, setLocalValue] = useState<string>(value);
  const [matchingAutoCompleteOptions, setMatchingAutoCompleteOptions] =
    useState<Array<{ value: string; label: string }>>([]);
  const [arrowCounter, setArrowCounter] = useState<number>(-1);

  const active = autocompleteOptions.length > 0;

  const total = matchingAutoCompleteOptions.length;
  const option = matchingAutoCompleteOptions[arrowCounter];
  let screenReaderSelectionText = "";
  if (total !== 0 && value)
    screenReaderSelectionText = option
      ? `${option.label} (${arrowCounter + 1}/${total})`
      : `${total} match${
          total > 1 ? "es" : ""
        } found for ${value}. Use the up and down arrow keys to browse the options. Use the enter or tab key to choose a selection or continue typing to narrow down the options.`;

  const lookupAutoComplete = () => {
    if (!active) return;
    if (!value) return close();
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = createAutocompleteTimeout();
  };

  const handleClose = () => {
    if (resultsRef.current) resultsRef.current.scrollTop = 0;

    setArrowCounter(-1);
    setMatchingAutoCompleteOptions([]);
  };

  const handleChange = (value: string) => {
    setLocalValue(value);
    onChange && onChange(value);
    lookupAutoComplete();
  };

  const handleBlur = () => {
    if (!active) return;
    setTimeout(() => {
      handleClose();
    }, BLUR_CLOSE_DELAY);
  };

  const handleAutocompleteItemHover = (index: number) => {
    setArrowCounter(index);
  };

  const handleSelect = (selection: AutoCompleteOption) => {
    const value = useValueForInput ? selection.value : selection.label;
    setLocalValue(value);
    handleClose();
  };

  const scrollToSelection = () => {
    if (!resultsRef.current) return;
    const nodes = resultsRef.current.querySelectorAll("li");
    const li = nodes[arrowCounter];
    if (!li) return;
    resultsRef.current.scrollTop = li.offsetTop - 50;
  };

  const handleArrowDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    if (arrowCounter + 1 < total) setArrowCounter(arrowCounter + 1);
    scrollToSelection();
  };
  const handleArrowUp = (e: React.KeyboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    if (arrowCounter >= 0) setArrowCounter(arrowCounter - 1);
    scrollToSelection();
  };

  const handleEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
    const selection = matchingAutoCompleteOptions[arrowCounter];
    if (!selection) return;

    e.preventDefault();

    handleSelect(selection);
  };

  const handleTab = (e: React.KeyboardEvent<HTMLInputElement>) => {
    const selection = matchingAutoCompleteOptions[arrowCounter];
    if (!selection) return;

    handleSelect(selection);
  };
  const handleClick = (item: AutoCompleteOption) => {
    handleSelect(item);
    if (inputRef.current) inputRef.current.focus();
  };

  const findAllMatches = (normalizedValue: string) =>
    autocompleteOptions.filter((option) => {
      const mainMatch = option.value.includes(normalizedValue);

      if (mainMatch) return true;

      if (matchAgainstOptionLabel) {
        const labelMatch = normalizeStringInput(option.label).includes(
          normalizedValue
        );

        if (labelMatch) return true;
      }

      if (option.alias) return normalizedValue.match(option.alias);

      return false;
    });

  const findBestMatches = (
    totalOptions: AutoCompleteOption[],
    normalizedValue: string
  ) => {
    totalOptions.sort((a, b) => {
      const indexA = a.value.indexOf(normalizedValue);
      const indexB = b.value.indexOf(normalizedValue);

      if (indexA === indexB) {
        return 0;
      }

      if (indexA === -1) {
        return 1;
      }
      if (indexB === -1) {
        return -1;
      }

      if (indexA < indexB) {
        return -1;
      } else if (indexB < indexA) {
        return 1;
      }

      return 0;
    });

    return totalOptions.slice(0, MAX_NUMBER_OF_MATCHING_RESULTS);
  };

  const createAutocompleteTimeout = () =>
    setTimeout(() => {
      if (!value) return close();

      const normalizedValue = normalizeStringInput(value);
      setMatchingAutoCompleteOptions([]);

      const totalOptions = findAllMatches(normalizedValue);

      setMatchingAutoCompleteOptions(
        findBestMatches(totalOptions, normalizedValue)
      );
    }, AUTOCOMPLETE_DELAY);

  const handleKeydown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "ArrowDown") {
      handleArrowDown(e);
    } else if (e.key === "ArrowUp") {
      handleArrowUp(e);
    } else if (e.key === "Enter") {
      handleEnter(e);
    } else if (e.key === "Tab") {
      handleTab(e);
    }
  };

  return (
    <div className={styles.autocompleteContainer}>
      <label className="sr-only" aria-hidden htmlFor={inputId}>
        {label}
      </label>
      <input
        id={inputId}
        ref={inputRef}
        value={localValue}
        type="text"
        placeholder={placeholder}
        className={`input ${inputClassName} ${hasError ? "error" : ""}`}
        autoComplete="off"
        autoCapitalize="none"
        autoCorrect="off"
        spellCheck="false"
        onChange={(e) => handleChange(e.target.value)}
        onBlur={handleBlur}
        onKeyDown={handleKeydown}
      />
      <div role="status" aria-live="polite" className={`sr-only`}>
        {screenReaderSelectionText}
      </div>
      {total > 0 && (
        <ul ref={resultsRef} className={styles.autocompleteResults}>
          {matchingAutoCompleteOptions.map((item, index) => (
            <li
              key={index}
              className={`${styles.autocompleteResult} ${
                index === arrowCounter && styles.isActive
              }`}
              onClick={() => handleClick(item)}
              onMouseOver={() => handleAutocompleteItemHover(index)}
            >
              <TextWithMagicSymbol text={item.label} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default AutocompleteInput;
